In [27]:
import os
import boto3
import s3fs

session = boto3.Session(
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1"
)
s3_client = session.client("s3")

import knowledge_retrieval as rag 

rag.set_boto3_session(session)

x = rag.retrieve_context("What is retention")
print(len(x["sources"]))
 
out = rag.ask("What is retention")
print(out["answer"])

6
# What is Retention

**Retention** in papermaking refers to the ability to keep fine particles (fines, fillers, and other additives) in the paper sheet during the forming process, rather than losing them through the forming fabric into the white water system.

## Key Aspects of Retention:

### 1. **Basic Definition**
Retention is the measure of how much of the small particles added to the paper furnish actually remain in the final sheet. This includes:
- Fine fiber particles (fines)
- Mineral fillers (like calcium carbonate, kaolin, talc)
- Chemical additives

### 2. **Retention Mechanisms**
According to the technical literature, retention occurs through three principal mechanisms [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]:
- **Charge neutralization**
- **Patch-flocculation**
- **Bridging** (the most common in practice)
- **Network flocculation** (used in multi-component systems)

### 3. **Retention Aids**
Chemical polymers called retention aids are used to improve retention. Common types include [papermaking_science_technology.pdf:d6f6f20ccb65b658:1250:0]:
- Polyacrylamide (PAM) - main polymer for bridging flocculation
- Polyethylene imine (PEI) - for patch flocculation
- Polyethylene oxide (PEO) - for network flocculation with fines
- Various cationic polymers that interact with negatively charged fibers and fines

### 4. **Benefits of Good Retention**
[chemicals_fundamentals.pdf:ab0dbcd601d60067:5:0]:

**On the forming fabric:**
- Better drainage and dewatering
- Less abrasion

**For production:**
- Increased production rates
- Steam consumption savings
- Reduced COD and BOD in effluent

**For paper properties:**
- Higher filler levels possible
- Better printability
- Higher opacity
- Less linting and dusting
- Reduced two-sidedness

### 5. **Challenges**
- **Anionic trash** significantly impacts retention aid efficiency, as cationic retention aids cannot distinguish between negative charges from trash versus fiber surfaces [chemicals_fundamentals.pdf:ab0dbcd601d60067:5:0]
- There's a trade-off between retention, drainage, and formation - improving one can impair the others [papermaking_science_technology.pdf:d6f6f20ccb65b658:1254:0]

### 6. **Modern Systems**
Modern paper machines typically use **multi-component retention systems** rather than single polymers to achieve better retention and drainage without sacrificing paper formation [papermaking_science_technology.pdf:d6f6f20ccb65b658:1254:0].

In [2]:
print(session.client("sts").get_caller_identity())

{'UserId': 'AROA3MADJBNORKPXPCTFN:Miguel.Angel.Gonzalez@dssmith.com', 'Account': '781690932061', 'Arn': 'arn:aws:sts::781690932061:assumed-role/AWSReservedSSO_DatafactoryDeveloper_119239aa22a5c202/Miguel.Angel.Gonzalez@dssmith.com', 'ResponseMetadata': {'RequestId': '32ce5f6b-ed7b-4a6a-9cd7-dc8cc966a59c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '32ce5f6b-ed7b-4a6a-9cd7-dc8cc966a59c', 'x-amz-sts-extended-request-id': 'MTpldS13ZXN0LTE6UzoxNzczNzQxMTM5ODY1OlI6SlhzNW5qczg=', 'content-type': 'text/xml', 'content-length': '525', 'date': 'Tue, 17 Mar 2026 09:52:19 GMT'}, 'RetryAttempts': 0}}

In [4]:
import os
import boto3
import s3fs

session = boto3.Session(
    #profile_name="DatafactoryAdministrator-636452271875",
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1"
)
s3 = session.client("s3")


creds = session.get_credentials().get_frozen_credentials()

fs = s3fs.S3FileSystem(
    anon=False,
    key=creds.access_key,
    secret=creds.secret_key,
    token=creds.token,
    client_kwargs={"region_name": 'eu-west-1'}
)

In [5]:
import pandas as pd
import io
import importlib
import process_data_tools as pdt
 
importlib.reload(pdt)
pdt.set_filesystem(fs)

In [68]:
import importlib
import process_data_tools as pdt
 
importlib.reload(pdt)
 
df_all = pdt.load_turnup_data()
print(df_all.shape)
print(df_all.head())

(3289, 501)
           Wedge_Time  MBS_SCT_MD  MBS_SCT_CD   MBS_Burst  MBS_CMT30  \
0 2025-06-04 13:50:00        3.23        2.00  284.779999      153.0
1 2025-06-04 14:44:00        3.41        2.01  280.779999      153.0
2 2025-06-04 15:39:00        3.29        2.02  276.450012      153.0
3 2025-06-04 16:38:00        3.29        2.02  276.450012      153.0
4 2025-06-05 00:24:00        3.33        1.96  276.700012      153.0

   MBS_Current_reel_ID AB_Grade_ID  Stock_pump_power        Speed  \
0             12503787     3200115        740.900024  1138.900024
1             12503788     3200115        737.600037  1139.000000
2             12503789     3200115        740.100037  1138.099976
3             12503791     3200115        738.600037  1137.699951
4             12503799     3300100        746.000000  1250.000000

   Current_reel_weight  ...  Electricity_index  Electricity_sqm  SCT_CD_index  \
0         53111.402344  ...         318.335876         0.036682      0.017364
1         52276.996094  ...         308.962219         0.035522      0.017490
2         52445.812500  ...         322.434875         0.037054      0.017576
3          2240.570801  ...         309.510925         0.035936      0.017377
4         50790.199219  ...         343.581940         0.034390      0.019589

   retention  Wedge_Date  Overprocessing_percentage  Overprocessing_SCT_CD  \
0   0.854447  2025-06-04                   0.106112               0.025641
1   0.855567  2025-06-04                   0.100343               0.030769
2   0.853382  2025-06-04                   0.093886               0.035897
3   0.854009  2025-06-04                   0.093886               0.035897
4   0.839568  2025-06-05                   0.324008               0.264516

   Overprocessing_Burst  Overprocessing_CMT30  Overprocessing_cost__€/T_
0              0.186583                   NaN                 912.381853
1              0.169917                   NaN                 832.776540
2              0.151875                   NaN                 744.315189
3              0.151875                   NaN                 735.869991
4              0.383500                   NaN                1799.130247

[5 rows x 501 columns]

In [2]:
cols = pdt.get_available_columns()
print(len(cols))
print(cols[:30])

501
['Wedge_Time', 'MBS_SCT_MD', 'MBS_SCT_CD', 'MBS_Burst', 'MBS_CMT30', 'MBS_Current_reel_ID', 'AB_Grade_ID', 'Stock_pump_power', 'Speed', 'Current_reel_weight', 'Current_reel_width', 'Current_reel_length', 'Production_Rate__T/h_', 'Current_basis_weight', 'Current_reel_moisture_average(reel)', 'Actual_moisture', 'Current_reel_dry_average', 'BSW_2_sigma', 'Mois_Size_Press_2_sigma', 'Mois_2_sigma', 'Contact_pressure_reel_holders', 'Reel_discharge_pressure', 'Draw_meaurement_pope_reel_FS', 'Draw_measurement_pope_reel_DS', 'Total_draw_measurement_pope_reel', 'Contact_pressure_secondary_arm_OS', 'Contact_pressure_secondary_arm_DS', 'Retentionsmittel_Menge_l/h__0..9000_l/h__', 'Bentonitmenge_z._Mischrohr__-10..9000_l/h_', 'Bentonitmenge_z._Siebwasserturm__-10..9000_l/h_']

In [14]:
import pandas as pd

In [15]:
mask = pd.Series(True, index=df_all.index)

In [24]:
df_small = pdt.get_wide_process_data(
    start="2025-10-01",
    end="2025-10-10",
    grade='6010120',
    columns=["MBS_Current_reel_ID", "Wedge_Time", "AB_Grade_ID"]
)
 
print(df_small.head())
print(df_small.shape)

      MBS_Current_reel_ID          Wedge_Time AB_Grade_ID
1403             12506543 2025-10-01 12:19:00     6010120
1404             12506545 2025-10-01 14:12:00     6010120
1405             12506546 2025-10-01 14:18:00     6010120
1406             12506547 2025-10-01 15:24:00     6010120
1407             12506549 2025-10-01 16:39:00     6010120
(53, 3)

In [25]:
fx = pdt.get_feature_snapshot(
    grade="6010120"
)
 
print(fx.shape)
print(fx.head())

(980, 501)
            Wedge_Time  MBS_SCT_MD  MBS_SCT_CD   MBS_Burst   MBS_CMT30  \
80 2025-06-09 14:05:00        3.55        2.16  273.869995  193.159073
81 2025-06-09 15:03:00        3.85        2.31  281.910004  193.159073
82 2025-06-09 15:50:00        3.68        2.24  287.519989  197.000000
83 2025-06-09 16:38:00        3.68        2.24  287.519989  197.000000
84 2025-06-10 00:09:00        3.66        2.18  275.779999  187.000000

    MBS_Current_reel_ID AB_Grade_ID  Stock_pump_power        Speed  \
80             12503923     6010120        833.000000  1230.650024
81             12503924     6010120        856.299988  1230.150024
82             12503925     6010120        852.299988  1230.199951
83             12503926     6010120        851.900024  1230.400024
84             12503936     6010120        852.299988  1229.849976

    Current_reel_weight  ...  Electricity_index  Electricity_sqm  \
80         18063.437500  ...         289.860168         0.035001
81         52172.671875  ...         292.710083         0.035091
82         51081.910156  ...         296.136841         0.035694
83         51583.890625  ...         293.000488         0.035136
84         52902.160156  ...         289.924133         0.035023

    SCT_CD_index  retention  Wedge_Date  Overprocessing_percentage  \
80      0.017896   0.793769  2025-06-09                   0.048881
81      0.019266   0.805398  2025-06-09                   0.085466
82      0.018595   0.810194  2025-06-09                   0.078774
83      0.018677   0.822474  2025-06-09                   0.078774
84      0.018049   0.831575  2025-06-10                   0.037113

    Overprocessing_SCT_CD  Overprocessing_Burst  Overprocessing_CMT30  \
80               0.053659                   NaN              0.044103
81               0.126829                   NaN              0.044103
82               0.092683                   NaN              0.064865
83               0.092683                   NaN              0.064865
84               0.063415                   NaN              0.010811

    Overprocessing_cost__€/T_
80                  54.359962
81                  54.764909
82                  80.116584
83                  80.469293
84                  13.344868

[5 rows x 501 columns]

In [8]:
import assistant_router as ar

In [29]:
out = ar.answer("What is retention in papermaking?")
print(out["answer"])

# What is Retention in Papermaking?

Retention in papermaking refers to **the ability to keep fibers, fines (small fiber fragments), and fillers (mineral pigments) in the paper sheet during the manufacturing process**, rather than losing them through the wire mesh as the water drains away.

## Two Types of Retention Mechanisms

### 1. **Mechanical Retention (Filtration)**
This is the physical trapping of particles as water drains through the forming fiber mat. Mechanical retention is:
- Size-dependent, with retention increasing as particle size increases
- Very low for single pigment particles before a fibrous mat forms
- Enhanced after web formation through entrapment in fiber lumen or between fibrils [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0]

### 2. **Chemical Retention (Adsorption)**
This involves using chemical additives (retention polymers) to attach particles to fiber surfaces through co-flocculation before web build-up [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0].

## Chemical Retention Mechanisms

There are **three principal categories** of chemical retention mechanisms:

1. **Charge neutralization**
2. **Patch-flocculation**
3. **Bridging** - the most common in practice [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]

The chemical retention process occurs in stages:
- First, polymer adsorbs onto furnish solids surfaces (fines and fillers adsorb proportionally more due to larger specific surface area, though fibers adsorb faster)
- This is followed by homo- and heteroflocculation of particles [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]

## Modern Retention Systems

On modern paper machines, **single-polymer retention systems are seldom adequate**. Dual- or multi-component systems are increasingly applied, which can improve retention and drainage without sacrificing formation [papermaking_science_technology.pdf:d6f6f20ccb65b658:1254:0].

## Importance

Good retention is critical because it:
- Achieves more homogeneous sheet structure
- Improves product economy
- Affects drainage and sheet structure
- Reduces material losses to the white water system

In [9]:
out = ar.answer("Show electricity data")
print(out["message"])

Loaded 7238 rows from dataset.

In [2]:
import importlib
import prediction_tools as pt
 
importlib.reload(pt)
print(pt.list_available_components())

['fibre', 'steam', 'electricity', 'starch']

In [3]:
import process_data_tools as pdt
 
df_all = pdt.load_turnup_data()
row = df_all.iloc[0]

In [5]:
print("steam:", len(pt.get_required_features("steam")))
print("electricity:", len(pt.get_required_features("electricity")))
print("starch:", len(pt.get_required_features("starch")))
print("fibre:", pt.get_required_features("fibre"))

steam: 24
electricity: 24
starch: 12
fibre: ['Current_basis_weight', 'Starch_uptake__g/m2_', 'Current_reel_moisture_average(reel)']

In [6]:
print("fibre:", pt.predict_component_from_row(row, "fibre"))
print("steam:", pt.predict_component_from_row(row, "steam"))
print("electricity:", pt.predict_component_from_row(row, "electricity"))
print("starch:", pt.predict_component_from_row(row, "starch"))

fibre: 127.01268768310547
steam: -985.1257303052079
electricity: 207.9926614504653
starch: 5.307907057754705

In [3]:
import importlib
import shap_tools as st
 
importlib.reload(st)
print(st.list_shap_components())

['steam', 'electricity', 'starch']

In [4]:
res = st.explain_grade_component(
    component="electricity",
    grade_id="6010120"
)
 
print(type(res))
print(res["component"])
print(res["grade_id"])
print(res["Xe"].shape)
print(len(res["feature_names"]))
print(res["shap_values"].shape)

PermutationExplainer explainer: 201it [02:48,  1.19it/s]

<class 'dict'>
electricity
6010120
(200, 24)
24
(200, 24)

In [5]:
fig = st.build_shap_beeswarm_figure(res, max_features=15)
fig.show()

In [27]:
import importlib
import assistant_router as ar
 
importlib.reload(ar)

In [130]:
import importlib
import aws_context as awsc
import knowledge_retrieval as kr
 
session = boto3.Session(
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1",
)
 
awsc.set_session(session)
 
importlib.reload(kr)
kr.set_boto3_session(session)
 
out = kr.ask("What is retention in papermaking?")
print(out["answer"])

# What is Retention in Papermaking?

Retention in papermaking refers to **the ability to keep fibers, fines (small fiber fragments), and fillers (mineral pigments) in the paper sheet during the manufacturing process**, rather than losing them through drainage water as the paper web is formed.

## Two Types of Retention Mechanisms

### 1. **Mechanical Retention (Filtration)**
This is the physical trapping of particles as water drains through the forming fiber mat. Mechanical retention is:
- Size-dependent, with retention increasing as particle size increases
- Very low for single pigment particles before a fibrous mat forms
- Enhanced when fine pigments are trapped within fiber lumen or between fibrils on the fiber surface [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0]

### 2. **Chemical Retention (Adsorption)**
This involves using chemical additives (retention polymers) to attach particles to fiber surfaces through co-flocculation before web build-up [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0].

## Chemical Retention Mechanisms

The mechanisms can be divided into **three principal categories**:

1. **Charge neutralization**
2. **Patch-flocculation**
3. **Bridging** - the most common in practice [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]

## Why Retention Matters

Good retention provides several benefits:
- **Better product economy** - less material lost to wastewater
- **More homogeneous sheet structure**
- **Improved filler retention** - agglomerated fillers are more thoroughly retained due to their larger size
- **Enhanced dewatering** [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0]

## Modern Retention Systems

On modern paper machines, single-polymer retention systems are seldom adequate. **Dual- or multi-component systems** are increasingly applied, which can improve retention and drainage without sacrificing paper formation [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0; 1254:0].

In [29]:
import boto3
import importlib
import aws_context as awsc
import knowledge_retrieval as kr
import process_data_tools as pdt
import prediction_tools as pt
import shap_tools as st
import assistant_router as ar
import cost_driver_tools as cdt
 
session = boto3.Session(
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1",
)
 
awsc.set_session(session)
 
importlib.reload(kr)
kr.set_boto3_session(session)
 
importlib.reload(pdt)
importlib.reload(pt)
importlib.reload(st)
importlib.reload(ar)
importlib.reload(cdt)

c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning:

Trying to unpickle estimator StandardScaler from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning:

Trying to unpickle estimator Ridge from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning:

Trying to unpickle estimator Pipeline from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning:

Trying to unpickle estimator GridSearchCV from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations

In [2]:
out = ar.answer("What is retention in papermaking?")
print(out["type"])
print(out["answer"])

knowledge
# What is Retention in Papermaking?

Retention in papermaking refers to **the ability to keep solid materials (fibers, fines, and fillers) in the paper sheet during the manufacturing process**, rather than losing them through drainage water as the paper web is formed.

## Key Aspects of Retention:

### 1. **Two Types of Retention Mechanisms**

**Mechanical Retention (Filtration):**
- Occurs after formation of a fibrous mat where filtration takes place
- Size-dependent mechanism - retention increases with increasing particle size
- Very fine pigment can be trapped within fiber lumen or between fibrils on the fiber surface
- Coarse particles are poorly retained initially [papermaking_science_technology.pdf:d6f6f20ccb65b658:1216:1]

**Chemical Retention (Adsorption):**
- Involves special chemical additives that cause particles to attach to fiber surfaces through co-flocculation before web build-up
- Results in more homogeneous sheet structure with better product economy
- Polymers are normally added to the whole furnish [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0]

### 2. **Three Principal Retention Mechanisms**

The mechanisms can be divided into three categories:
- **Charge neutralization**
- **Patch-flocculation**
- **Bridging** (the most common in practice)

On modern paper machines, single-polymer retention systems are seldom sufficient, and dual- or multi-component systems are increasingly applied [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]

### 3. **Factors Affecting Retention**

- **Particle characteristics**: Particle shape affects retention - clay and talc platelets display better retention than blocky chalk [papermaking_science_technology.pdf:d6f6f20ccb65b658:1217:0]
- **Particle size**: Relative contributions of filtration and adsorption vary with filler particle size [papermaking_science_technology.pdf:d6f6f20ccb65b658:1216:1]
- **Polymer type, molecular weight, and charge**
- **Chemical environment and turbulence** [papermaking_science_technology.pdf:d6f6f20ccb65b658:1218:0]

### 4. **Trade-offs**

During papermaking, **retention, drainage, and formation are all related and opposed to each other** - improving one could impair the others. This has led to evolution from single-polymer to multi-component retention systems [papermaking_science_technology.pdf:d6f6f20ccb65b658:1254:0]

In [19]:
out = ar.answer_shap(
    component="electricity",
    grade_id="6010120"
)
 
print(out["type"])
print(out["component"])
print(out["grade_id"])
print(out["Xe_shape"])

shap
electricity
6010120
(200, 24)

In [8]:
df = cdt.run_cost_driver_analysis(
    target_range=(target_range[0].strftime("%F"), target_range[1].strftime("%F")),
    baseline_range=(baseline_range[0].strftime("%F"), baseline_range[1].strftime("%F")),
    cost_component="electricity",
    grade="6010120"
)
 
print(df.head())

['historic' 'current']
['historic' 'current']
  AB_Grade_ID                                variable  contribution  \
0     6010120                               retention      7.199182
1     6010120                    Vacuum_suction_box_9     -0.004741
2     6010120                            Draw_PD4-PD5     -0.000016
3     6010120  Vacuum_presszone_of_suction-press_roll      0.086551
4     6010120                                   Speed     -1.257426

   value_change
0     -0.058920
1      0.000060
2     -0.000111
3     -0.007861
4    135.002686

In [11]:
import importlib
import assistant_router as ar
 
importlib.reload(ar)

In [12]:
out = ar.answer_cost_driver_analysis(
    target_range=(target_range[0].strftime("%F"), target_range[1].strftime("%F")),
    baseline_range=(baseline_range[0].strftime("%F"), baseline_range[1].strftime("%F")),
    cost_component="electricity",
    grade="6010120"
)
 
print(out["type"])
print(out["component"])
print(out["n_rows"])
print(out["summary"]["top_increase"])
print(out["summary"]["top_decrease"])

['historic' 'current']
['historic' 'current']
cost_driver_analysis
electricity
24
[{'AB_Grade_ID': '6010120', 'variable': 'retention', 'contribution': 7.199182373988985, 'value_change': -0.058920085430145264}, {'AB_Grade_ID': '6010120', 'variable': 'Lip_settings', 'contribution': 0.47086823672230277, 'value_change': -0.22878170013427734}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wire_suction_box_2', 'contribution': 0.29627876250968593, 'value_change': -0.062469482421875}, {'AB_Grade_ID': '6010120', 'variable': 'White_water_temperature', 'contribution': 0.10862080205838931, 'value_change': 2.075550079345703}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_presszone_of_suction-press_roll', 'contribution': 0.0865511824498303, 'value_change': -0.007861435413360596}]
[{'AB_Grade_ID': '6010120', 'variable': 'Consistency_white_water', 'contribution': -7.63267031502063, 'value_change': 0.8561058044433594}, {'AB_Grade_ID': '6010120', 'variable': 'Speed', 'contribution': -1.2574256420729981, 'value_change': 135.002685546875}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wire_suction_box_1', 'contribution': -0.37471828624609355, 'value_change': -0.033886849880218506}, {'AB_Grade_ID': '6010120', 'variable': 'Draw_PD3-PD4', 'contribution': -0.05181163338638293, 'value_change': 0.025256991386413574}, {'AB_Grade_ID': '6010120', 'variable': 'SpeedSizer_Linepressure_FS', 'contribution': -0.03748045904023693, 'value_change': 4.680225372314453}]

In [15]:
out = ar.answer_cost_driver_analysis(
    target_range=(target_range[0].strftime("%F"), target_range[1].strftime("%F")),
    baseline_range=(baseline_range[0].strftime("%F"), baseline_range[1].strftime("%F")),
    cost_component="electricity",
    grade="6010120",
    lang="en"
)
 
print(out["narrative"])

['historic' 'current']
['historic' 'current']
For grade 6010120, the cost change is mainly explained by the following factors (top 20% by contribution):
Cost-reducing drivers:
- Consistency white water increased (+0.86)
- Speed increased (+135.00)
- Vacuum wire suction box 1 decreased (-0.03)
Cost-increasing drivers:
- Retention decreased (-0.06)
- Lip settings decreased (-0.23)

In [16]:
import query_parser as qp
 
print(qp.parse_query("Explain electricity cost drivers for grade 6010120"))
print(qp.parse_query("Show SHAP for starch in 6010120"))
print(qp.parse_query("Predict fibre cost for grade 6010120"))

{'intent': 'cost_driver', 'cost_component': 'electricity', 'grade': '6010120', 'raw_query': 'Explain electricity cost drivers for grade 6010120'}
{'intent': 'shap', 'cost_component': 'starch', 'grade': '6010120', 'raw_query': 'Show SHAP for starch in 6010120'}
{'intent': 'prediction', 'cost_component': 'fibre', 'grade': '6010120', 'raw_query': 'Predict fibre cost for grade 6010120'}

In [17]:
import importlib
import assistant_router as ar
 
importlib.reload(ar)

In [18]:
out = ar.answer("Show SHAP for electricity in grade 6010120")
print(out["type"])
print(out["component"])
print(out["grade_id"])

PermutationExplainer explainer: 201it [00:13,  8.30it/s]

shap
electricity
6010120

In [21]:
out['figure']

In [22]:
out = ar.answer("Predict fibre cost for grade 6010120")
print(out)

{'type': 'prediction', 'component': 'fibre', 'grade': '6010120', 'prediction': 128.03720092773438}

In [32]:
out = ar.answer("Explain electricity cost drivers for grade 6010120 for week 13")
print(out["target_range"])
print(out["baseline_range"])
print(out["narrative"])

['historic']

KeyError: 'variable'

In [31]:
print(out)

{'type': 'cost_driver_analysis', 'component': 'electricity', 'grade': '6010120', 'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 8), datetime.date(2026, 3, 8)), 'used_default_ranges': True, 'n_rows': 24, 'raw':    AB_Grade_ID                                variable  contribution  \
0      6010120                               retention      7.199182
1      6010120                    Vacuum_suction_box_9     -0.004741
2      6010120                            Draw_PD4-PD5     -0.000016
3      6010120  Vacuum_presszone_of_suction-press_roll      0.086551
4      6010120                                   Speed     -1.257426
5      6010120                 Vacuum_uhle-box_Pick-Up     -0.020846
6      6010120               Vacuum_wire_suction_box_1     -0.374718
7      6010120             Vacuum_uhle-box_bottom_felt      0.048268
8      6010120                 Consistency_white_water     -7.632670
9      6010120          pH_measurement_white_water_B41      0.002145
10     6010120                Moisture_out_of_PreDryer     -0.001702
11     6010120              SpeedSizer_Linepressure_FS     -0.037480
12     6010120                             Draw_PD5-SS      0.065144
13     6010120               Vacuum_wire_suction_box_2      0.296279
14     6010120                            Draw_PD3-PD4     -0.051812
15     6010120              Vacuum_sheet_seperator_box     -0.013034
16     6010120                          PickUp_Tension      0.002320
17     6010120                             Draw_PS-PD1      0.053407
18     6010120                            Lip_settings      0.470868
19     6010120            Consistency_starch_main_line     -0.000341
20     6010120                 White_water_temperature      0.108621
21     6010120                              Draw_WS-PS      0.070233
22     6010120                  Vacuum_wet_suction_box     -0.007682
23     6010120                   Vacuum_suction_box_11     -0.000550

    value_change
0      -0.058920
1       0.000060
2      -0.000111
3      -0.007861
4     135.002686
5      -0.108954
6      -0.033887
7      -0.150583
8       0.856106
9       0.010220
10      0.015002
11      4.680225
12     -0.056045
13     -0.062469
14      0.025257
15      0.000147
16     -0.093565
17      0.235284
18     -0.228782
19      0.024271
20      2.075550
21     -0.002788
22     -0.000068
23     -0.000097  , 'summary': {'top_increase': [{'AB_Grade_ID': '6010120', 'variable': 'retention', 'contribution': 7.199182373988991, 'value_change': -0.058920085430145264}, {'AB_Grade_ID': '6010120', 'variable': 'Lip_settings', 'contribution': 0.4708682367223031, 'value_change': -0.22878170013427734}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wire_suction_box_2', 'contribution': 0.2962787625096862, 'value_change': -0.062469482421875}, {'AB_Grade_ID': '6010120', 'variable': 'White_water_temperature', 'contribution': 0.10862080205838937, 'value_change': 2.075550079345703}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_presszone_of_suction-press_roll', 'contribution': 0.08655118244983022, 'value_change': -0.007861435413360596}], 'top_decrease': [{'AB_Grade_ID': '6010120', 'variable': 'Consistency_white_water', 'contribution': -7.632670315020636, 'value_change': 0.8561058044433594}, {'AB_Grade_ID': '6010120', 'variable': 'Speed', 'contribution': -1.2574256420729992, 'value_change': 135.002685546875}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wire_suction_box_1', 'contribution': -0.3747182862460936, 'value_change': -0.033886849880218506}, {'AB_Grade_ID': '6010120', 'variable': 'Draw_PD3-PD4', 'contribution': -0.0518116333863829, 'value_change': 0.025256991386413574}, {'AB_Grade_ID': '6010120', 'variable': 'SpeedSizer_Linepressure_FS', 'contribution': -0.0374804590402369, 'value_change': 4.680225372314453}]}, 'narrative': 'No time intervals were specified, so the default periods were used: target=2026-03-09 to 2026-03-14, baseline=2026-02-08 to 2026-03-08.\n\nFor grade 6010120, the cost change is mainly explained by the following factors (top 20% by contribution):\nCost-reducing drivers:\n- Consistency white water increased (+0.86)\n- Speed increased (+135.00)\n- Vacuum wire suction box 1 decreased (-0.03)\nCost-increasing drivers:\n- Retention decreased (-0.06)\n- Lip settings decreased (-0.23)'}

In [24]:
import importlib
import query_parser as qp
 
importlib.reload(qp)
 
print(qp.parse_query(
    "Explain electricity cost drivers for grade 6010120 between 2025-01-10 and 2025-01-20 compared with 2024-12-10 and 2024-12-20"
))

{'intent': 'cost_driver', 'cost_component': 'electricity', 'grade': '6010120', 'target_range': ('2025-01-10', '2025-01-20'), 'baseline_range': ('2024-12-10', '2024-12-20'), 'raw_query': 'Explain electricity cost drivers for grade 6010120 between 2025-01-10 and 2025-01-20 compared with 2024-12-10 and 2024-12-20'}

In [25]:
import time_context as tc
 
x = tc.get_default_interval_ranges()
print(x)
 
msg = tc.build_default_ranges_message(
    target_range=x["target_range"],
    baseline_range=x["baseline_range"],
    used_any_default=True,
    lang="en",
)
print(msg)

{'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 8), datetime.date(2026, 3, 8)), 'min_date': Timestamp('2025-06-04 13:50:00'), 'max_date': Timestamp('2026-03-16 06:51:00')}
No time intervals were specified, so the default periods were used: target=2026-03-09 to 2026-03-14, baseline=2026-02-08 to 2026-03-08.

In [34]:
import importlib
import query_parser as qp
 
importlib.reload(qp)
 
print(qp.parse_query("Explain electricity cost drivers for grade 6010120 for week 13"))
print(qp.parse_query("Explain electricity cost drivers for grade 6010120 for day 2026-03-18"))
print(qp.parse_query("Explain electricity cost drivers for grade 6010120 for month February"))

{'intent': 'cost_driver', 'cost_component': 'electricity', 'grade': '6010120', 'target_range': (datetime.date(2026, 3, 23), datetime.date(2026, 3, 28)), 'baseline_range': (datetime.date(2026, 2, 23), datetime.date(2026, 3, 23)), 'raw_query': 'Explain electricity cost drivers for grade 6010120 for week 13'}
{'intent': 'cost_driver', 'cost_component': 'electricity', 'grade': '6010120', 'target_range': (datetime.date(2026, 3, 18), datetime.date(2026, 3, 19)), 'baseline_range': (datetime.date(2026, 2, 18), datetime.date(2026, 3, 18)), 'raw_query': 'Explain electricity cost drivers for grade 6010120 for day 2026-03-18'}
{'intent': 'cost_driver', 'cost_component': 'electricity', 'grade': '6010120', 'target_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'baseline_range': (datetime.date(2026, 1, 1), datetime.date(2026, 2, 1)), 'raw_query': 'Explain electricity cost drivers for grade 6010120 for month February'}

In [36]:
out = ar.answer("Explain electricity cost drivers for grade 6010120 for week 11")
print(out["target_range"])
print(out["baseline_range"])
print(out["narrative"])

['historic' 'current']
['historic' 'current']
(datetime.date(2026, 3, 9), datetime.date(2026, 3, 14))
(datetime.date(2026, 2, 9), datetime.date(2026, 3, 9))
For grade 6010120, the cost change is mainly explained by the following factors (top 20% by contribution):
Cost-reducing drivers:
- Consistency white water increased (+0.82)
- Speed increased (+135.19)
- Vacuum wire suction box 1 decreased (-0.03)
Cost-increasing drivers:
- Retention decreased (-0.06)
- Lip settings decreased (-0.23)

In [40]:
import importlib
import time_context as tc
import assistant_router as ar
 
importlib.reload(tc)
importlib.reload(ar)

In [43]:
out = ar.answer("Predict electricity cost for grade 6010120  for week 14")
 
print(out["target_range"])
print(out["prediction"])
print(out["message"])

(datetime.date(2026, 3, 30), datetime.date(2026, 4, 4))
291.50150341385165

In [44]:
import importlib
import process_data_tools as pdt
import assistant_router as ar
 
importlib.reload(pdt)
importlib.reload(ar)

In [51]:
out = ar.answer("Show SHAP for electricity in grade 6010120 between 2026-03-16 and 2026-03-21 compared with 2026-02-16 and 2026-03-16")
print(out["target_range"])
print(out["baseline_range"])
print(out["used_default_ranges"])
print(out["message"])
print(out["Xe_shape"])

('2026-03-16', '2026-03-21')
('2026-02-16', '2026-03-16')
False

(9, 24)

In [58]:
import importlib
import query_parser as qp
import time_context as tc
import assistant_router as ar
 
importlib.reload(qp)
importlib.reload(tc)
importlib.reload(ar)

In [72]:
out = ar.answer("Show data for grade 6010120 from 2026-03-01 to 2026-03-10")
print(out["target_range"])
print(out["n_rows"])

('2026-03-01', '2026-03-10')
51

In [73]:
out

{'type': 'process_data',
 'grade': '6010120',
 'target_range': ('2026-03-01', '2026-03-10'),
 'used_default_range': False,
 'n_rows': 51,
 'data':               Wedge_Time  MBS_SCT_MD  MBS_SCT_CD   MBS_Burst   MBS_CMT30  \
 3070 2026-03-01 15:02:00        4.02        2.12  284.429993  193.159073
 3071 2026-03-01 15:41:00        4.24        2.10  299.739990  194.000000
 3072 2026-03-01 16:38:00        4.24        2.10  299.739990  194.000000
 3073 2026-03-02 00:43:00        4.07        2.11  295.769989  196.000000
 3074 2026-03-02 01:30:00        4.05        2.11  296.679993  196.000000
 3075 2026-03-02 02:18:00        3.86        1.98  283.049988  199.000000
 3076 2026-03-02 03:06:00        4.22        2.15  299.820007  199.000000
 3077 2026-03-02 03:54:00        4.09        2.15  296.549988  199.000000
 3078 2026-03-02 04:42:00        4.13        2.15  300.320007  199.000000
 3079 2026-03-02 05:29:00        4.28        2.23  308.260010  199.000000
 3080 2026-03-02 06:34:00        4.20        2.13  302.260010  199.000000
 3081 2026-03-02 08:13:00        4.12        2.07  305.959991  199.000000
 3082 2026-03-02 09:38:00        4.19        2.13  301.220001  199.000000
 3083 2026-03-02 10:30:00        4.06        2.15  282.000000  199.000000
 3084 2026-03-02 10:48:00        4.08        2.20  297.869995  199.000000
 3085 2026-03-02 12:37:00        4.02        2.09  283.260010  195.000000
 3086 2026-03-02 14:10:00        3.93        2.06  287.859985  196.000000
 3087 2026-03-02 14:56:00        4.11        2.14  282.040009  192.000000
 3088 2026-03-02 15:42:00        4.16        2.19  295.950012  192.000000
 3089 2026-03-03 02:07:00        4.05        2.14  297.179993  196.000000
 3090 2026-03-03 02:55:00        4.02        2.12  297.299988  196.000000
 3091 2026-03-03 04:35:00        4.09        2.14  279.390015  199.000000
 3092 2026-03-03 06:27:00        4.06        2.17  286.570007  199.000000
 3093 2026-03-03 07:49:00        4.06        2.18  285.959991  194.000000
 3094 2026-03-03 08:31:00        4.14        2.23  288.000000  190.000000
 3095 2026-03-03 09:30:00        4.06        2.15  287.779999  190.000000
 3096 2026-03-03 10:17:00        3.80        2.04  271.769989  190.000000
 3097 2026-03-03 11:05:00        4.00        2.08  279.959991  186.000000
 3098 2026-03-03 11:52:00        4.07        2.05  286.899994  186.000000
 3099 2026-03-03 13:26:00        4.09        2.07  288.829987  187.000000
 3100 2026-03-03 14:13:00        4.14        2.12  287.649994  189.000000
 3101 2026-03-03 15:00:00        4.08        2.14  289.519989  189.000000
 3102 2026-03-03 15:47:00        4.07        2.12  296.040009  191.000000
 3103 2026-03-04 00:22:00        4.00        2.04  279.570007  188.000000
 3169 2026-03-09 00:18:00        4.09        2.10  291.950012  191.000000
 3170 2026-03-09 01:04:00        4.04        2.09  293.549988  189.000000
 3171 2026-03-09 01:50:00        4.06        2.13  290.179993  189.000000
 3172 2026-03-09 02:36:00        4.09        2.10  301.089996  185.000000
 3173 2026-03-09 03:22:00        4.28        2.16  302.649994  185.000000
 3174 2026-03-09 04:08:00        4.12        2.17  298.730011  190.000000
 3175 2026-03-09 04:54:00        4.17        2.19  298.049988  190.000000
 3176 2026-03-09 05:41:00        4.04        2.06  288.140015  196.000000
 3177 2026-03-09 07:13:00        4.06        2.06  281.640015  195.000000
 3178 2026-03-09 07:59:00        4.12        2.07  297.549988  195.000000
 3179 2026-03-09 10:17:00        3.99        1.96  279.640015  188.000000
 3180 2026-03-09 11:03:00        3.94        2.02  276.269989  188.000000
 3181 2026-03-09 11:50:00        4.06        2.09  300.609985  193.000000
 3182 2026-03-09 12:52:00        4.06        2.00  284.040009  186.000000
 3183 2026-03-09 13:55:00        3.97        2.00  278.429993  186.000000
 3184 2026-03-09 14:51:00        4.16        2.06  295.739990  193.000000
 3185 2026-03-09 15:54:00        4.06        2.10  299.260010  193.000000

       MBS_Current_reel_ID AB_Grade_ID  Stock_pump_power        Speed  \
 3070             12601557     6010120        848.600037  1234.150024
 3071             12601558     6010120        847.700012  1234.000000
 3072             12601560     6010120        847.000000  1234.099976
 3073             12601570     6010120        844.400024  1233.949951
 3074             12601571     6010120        846.299988  1233.849976
 3075             12601572     6010120        847.100037  1233.900024
 3076             12601573     6010120        846.700012  1233.949951
 3077             12601574     6010120        846.900024  1234.000000
 3078             12601575     6010120        847.799988  1233.900024
 3079             12601576     6010120        846.900024  1234.099976
 3080             12601578     6010120        866.299988  1250.800049
 3081             12601580     6010120        880.500000  1260.300049
 3082             12601582     6010120        891.299988  1260.699951
 3083             12601583     6010120        889.799988  1260.599976
 3084             12601584     6010120        893.100037  1260.550049
 3085             12601586     6010120        892.600037  1260.400024
 3086             12601588     6010120        892.200012  1260.599976
 3087             12601589     6010120        889.900024  1260.800049
 3088             12601590     6010120        892.900024  1260.599976
 3089             12601597     6010120        891.000000  1253.650024
 3090             12601598     6010120        889.900024  1252.750000
 3091             12601601     6010120        885.000000  1253.299927
 3092             12601603     6010120        920.900024  1271.599976
 3093             12601605     6010120        920.400024  1279.449951
 3094             12601606     6010120        918.700012  1279.349976
 3095             12601607     6010120        874.299988  1240.849976
 3096             12601608     6010120        870.900024  1241.099976
 3097             12601609     6010120        869.600037  1241.099976
 3098             12601610     6010120        865.100037  1241.000000
 3099             12601612     6010120        865.000000  1240.849976
 3100             12601613     6010120        866.100037  1240.900024
 3101             12601614     6010120        864.799988  1240.699951
 3102             12601615     6010120        865.000000  1240.800049
 3103             12601626     6010120        865.200012  1240.699951
 3169             12601756     6010120        879.000000  1280.449951
 3170             12601757     6010120        879.900024  1280.449951
 3171             12601758     6010120        879.200012  1280.400024
 3172             12601759     6010120        879.100037  1280.449951
 3173             12601760     6010120        871.799988  1280.000000
 3174             12601761     6010120        870.900024  1280.199951
 3175             12601762     6010120        872.200012  1280.050049
 3176             12601763     6010120        871.299988  1280.000000
 3177             12601765     6010120        868.900024  1279.900024
 3178             12601766     6010120        871.700012  1280.150024
 3179             12601769     6010120        871.500000  1280.099976
 3180             12601770     6010120        873.600037  1280.150024
 3181             12601771     6010120        870.200012  1280.150024
 3182             12601773     6010120        871.299988  1280.250000
 3183             12601774     6010120        870.900024  1280.199951
 3184             12601776     6010120        870.700012  1280.050049
 3185             12601777     6010120        874.500000  1280.000000

       Current_reel_weight  ...  Electricity_index  Electricity_sqm  \
 3070         51176.433594  ...         284.578613         0.034241
 3071         42418.375000  ...         297.485962         0.035809
 3072          3895.207520  ...         276.991486         0.033140
 3073         52486.570312  ...         286.448120         0.034230
 3074         51257.257812  ...         290.396423         0.034613
 3075         51393.695312  ...         290.931091         0.034483
 3076         51706.937500  ...         286.998047         0.034531
 3077         52402.054688  ...         289.931519         0.034925
 3078         52133.789062  ...         289.031616         0.034627
 3079         51265.667969  ...         289.044739         0.034645
 3080         17181.265625  ...         288.466705         0.034202
 3081         50380.097656  ...         291.140106         0.034496
 3082         41499.171875  ...         292.795715         0.034500
 3083         50928.371094  ...         293.479187         0.034598
 3084         18614.541016  ...         290.271606         0.034416
 3085         50489.746094  ...         293.197052         0.034685
 3086         50482.898438  ...         290.393341         0.034289
 3087         50498.847656  ...         292.473389         0.034734
 3088         50720.527344  ...         291.532196         0.034834
 3089         18246.410156  ...         291.943573         0.033394
 3090         53316.226562  ...         284.910736         0.033814
 3091          2840.906494  ...         295.689453         0.035502
 3092         51542.296875  ...         289.593445         0.034298
 3093         32624.527344  ...         285.521515         0.033700
 3094         39655.640625  ...         273.668335         0.032198
 3095         51439.382812  ...         288.461639         0.034512
 3096         50606.816406  ...         284.699493         0.033896
 3097         51404.386719  ...         280.065643         0.033211
 3098         51442.000000  ...         294.438568         0.034955
 3099         51312.957031  ...         288.065765         0.034395
 3100         50898.914062  ...         289.902252         0.034280
 3101         50636.039062  ...         277.083954         0.032859
 3102         50681.898438  ...         291.484711         0.034642
 3103         43723.562500  ...         284.872314         0.033729
 3169         51481.730469  ...         290.316589         0.034438
 3170         51691.437500  ...         295.898254         0.035108
 3171         51485.039062  ...         287.339020         0.034009
 3172         51547.527344  ...         280.419189         0.033446
 3173         51419.121094  ...         289.856049         0.034320
 3174         51093.914062  ...         288.271729         0.034175
 3175         50925.703125  ...         272.516663         0.032352
 3176         52152.031250  ...         284.465118         0.033789
 3177         51443.164062  ...         285.260193         0.033631
 3178         51426.007812  ...         284.106995         0.033721
 3179         51330.281250  ...         282.856873         0.033989
 3180         51180.546875  ...         291.465546         0.034665
 3181         51777.078125  ...         283.078857         0.033536
 3182         17378.990234  ...         289.291382         0.034465
 3183         52071.800781  ...         287.027161         0.034120
 3184         10285.191406  ...         284.808655         0.034023
 3185         51674.453125  ...         287.210114         0.034231

       SCT_CD_index  retention  Wedge_Date  Overprocessing_percentage  \
 3070      0.017624   0.831800  2026-03-01                   0.039125
 3071      0.017447   0.817575  2026-03-01                   0.036519
 3072      0.017556   0.818977  2026-03-01                   0.036519
 3073      0.017675   0.818287  2026-03-02                   0.044364
 3074      0.017698   0.820062  2026-03-02                   0.044364
 3075      0.016723   0.817761  2026-03-02                   0.020765
 3076      0.017867   0.809392  2026-03-02                   0.062228
 3077      0.017860   0.806711  2026-03-02                   0.062228
 3078      0.017945   0.809072  2026-03-02                   0.062228
 3079      0.018608   0.814639  2026-03-02                   0.081740
 3080      0.017977   0.808075  2026-03-02                   0.057350
 3081      0.017470   0.799408  2026-03-02                   0.042716
 3082      0.018099   0.805065  2026-03-02                   0.057350
 3083      0.018218   0.808166  2026-03-02                   0.062228
 3084      0.018555   0.806794  2026-03-02                   0.074423
 3085      0.017660   0.792279  2026-03-02                   0.036783
 3086      0.017440   0.796483  2026-03-02                   0.032169
 3087      0.018026   0.796162  2026-03-02                   0.040870
 3088      0.018327   0.803760  2026-03-02                   0.053065
 3089      0.018709   0.793356  2026-03-03                   0.051681
 3090      0.017872   0.800462  2026-03-03                   0.046803
 3091      0.017827   0.796786  2026-03-03                   0.059789
 3092      0.018322   0.800155  2026-03-03                   0.067106
 3093      0.018464   0.755773  2026-03-03                   0.056032
 3094      0.018940   0.791781  2026-03-03                   0.057416
 3095      0.017978   0.804319  2026-03-03                   0.037904
 3096      0.017128   0.793788  2026-03-03                   0.011074
 3097      0.017543   0.791352  2026-03-03                   0.010020
 3098      0.017255   0.783440  2026-03-03                   0.002703
 3099      0.017338   0.802384  2026-03-03                   0.010283
 3100      0.017924   0.812137  2026-03-03                   0.027884
 3101      0.018042   0.807584  2026-03-03                   0.032762
 3102      0.017838   0.801861  2026-03-03                   0.033289
 3103      0.017222   0.790541  2026-03-04                   0.005669
 3169      0.017708   0.792479  2026-03-09                   0.028411
 3170      0.017626   0.784134  2026-03-09                   0.020567
 3171      0.017998   0.778660  2026-03-09                   0.030323
 3172      0.017614   0.786502  2026-03-09                   0.012195
 3173      0.018246   0.775361  2026-03-09                   0.026829
 3174      0.018301   0.789783  2026-03-09                   0.042782
 3175      0.018443   0.790283  2026-03-09                   0.047660
 3176      0.017365   0.789005  2026-03-09                   0.032169
 3177      0.017477   0.788785  2026-03-09                   0.029466
 3178      0.017439   0.780193  2026-03-09                   0.031905
 3179      0.016311   0.784529  2026-03-09                  -0.013843
 3180      0.016999   0.789279  2026-03-09                   0.000791
 3181      0.017637   0.778621  2026-03-09                   0.031378
 3182      0.016797   0.759835  2026-03-09                  -0.009492
 3183      0.016824   0.772630  2026-03-09                  -0.009492
 3184      0.017268   0.781835  2026-03-09                   0.024061
 3185      0.017639   0.796267  2026-03-09                   0.033817

       Overprocessing_SCT_CD  Overprocessing_Burst  Overprocessing_CMT30  \
 3070           3.414629e-02                   NaN              0.044103
 3071           2.439020e-02                   NaN              0.048649
 3072           2.439020e-02                   NaN              0.048649
 3073           2.926824e-02                   NaN              0.059459
 3074           2.926824e-02                   NaN              0.059459
 3075          -3.414633e-02                   NaN              0.075676
 3076           4.878053e-02                   NaN              0.075676
 3077           4.878053e-02                   NaN              0.075676
 3078           4.878053e-02                   NaN              0.075676
 3079           8.780489e-02                   NaN              0.075676
 3080           3.902445e-02                   NaN              0.075676
 3081           9.756065e-03                   NaN              0.075676
 3082           3.902445e-02                   NaN              0.075676
 3083           4.878053e-02                   NaN              0.075676
 3084           7.317075e-02                   NaN              0.075676
 3085           1.951215e-02                   NaN              0.054054
 3086           4.878021e-03                   NaN              0.059459
 3087           4.390249e-02                   NaN              0.037838
 3088           6.829271e-02                   NaN              0.037838
 3089           4.390249e-02                   NaN              0.059459
 3090           3.414629e-02                   NaN              0.059459
 3091           4.390249e-02                   NaN              0.075676
 3092           5.853662e-02                   NaN              0.075676
 3093           6.341467e-02                   NaN              0.048649
 3094           8.780489e-02                   NaN              0.027027
 3095           4.878053e-02                   NaN              0.027027
 3096          -4.878067e-03                   NaN              0.027027
 3097           1.463411e-02                   NaN              0.005405
 3098          -2.326035e-08                   NaN              0.005405
 3099           9.756065e-03                   NaN              0.010811
 3100           3.414629e-02                   NaN              0.021622
 3101           4.390249e-02                   NaN              0.021622
 3102           3.414629e-02                   NaN              0.032432
 3103          -4.878067e-03                   NaN              0.016216
 3169           2.439020e-02                   NaN              0.032432
 3170           1.951215e-02                   NaN              0.021622
 3171           3.902445e-02                   NaN              0.021622
 3172           2.439020e-02                   NaN              0.000000
 3173           5.365858e-02                   NaN              0.000000
 3174           5.853662e-02                   NaN              0.027027
 3175           6.829271e-02                   NaN              0.027027
 3176           4.878021e-03                   NaN              0.059459
 3177           4.878021e-03                   NaN              0.054054
 3178           9.756065e-03                   NaN              0.054054
 3179          -4.390242e-02                   NaN              0.016216
 3180          -1.463416e-02                   NaN              0.016216
 3181           1.951215e-02                   NaN              0.043243
 3182          -2.439024e-02                   NaN              0.005405
 3183          -2.439024e-02                   NaN              0.005405
 3184           4.878021e-03                   NaN              0.043243
 3185           2.439020e-02                   NaN              0.043243

       Overprocessing_cost__€/T_
 3070                  54.532389
 3071                  60.110295
 3072                  60.484083
 3073                  74.076074
 3074                  74.172096
 3075                  95.011315
 3076                  93.535841
 3077                  93.499430
 3078                  93.939867
 3079                  93.941925
 3080                  94.988629
 3081                  94.967735
 3082                  95.630584
 3083                  95.371285
 3084                  94.943731
 3085                  67.921086
 3086                  74.847106
 3087                  47.415603
 3088                  47.120900
 3089                  77.315652
 3090                  74.550299
 3091                  93.756311
 3092                  95.036650
 3093                  61.302768
 3094                  34.182955
 3095                  33.631475
 3096                  33.737844
 3097                   6.787298
 3098                   6.764800
 3099                  13.469332
 3100                  27.200040
 3101                  27.129603
 3102                  40.594311
 3103                  20.351665
 3169                  40.678305
 3170                  27.123700
 3171                  27.187516
 3172                   0.014330
 3173                   0.031750
 3174                  33.926216

In [63]:
import importlib
import time_context as tc
import assistant_router as ar
 
importlib.reload(tc)
importlib.reload(ar)

In [64]:
out = ar.answer("Predict electricity for grade 6010120")
print(out["target_range"])
print(out["used_default_range"])
print(out["used_proxy_latest"])
print(out["prediction"])
print(out["message"])

(datetime.date(2026, 3, 23), datetime.date(2026, 3, 28))
True
True
291.50150341385165
No time interval was specified, so the next week was used by default: 2026-03-23 to 2026-03-28.

Because no observed process data is available for that interval, the prediction uses the latest available operating state for this grade as a proxy.

In [65]:
out = ar.answer("Predict fibre for grade 6010120 from 2026-03-01 to 2026-03-10")
print(out["target_range"])
print(out["used_proxy_latest"])
print(out["prediction"])
print(out["message"])

('2026-03-01', '2026-03-10')
False
127.40198323757785
The prediction is based on a representative operating state from the selected interval.

In [93]:
[v for v in df_all.columns if "starch" in v.lower()]

['Starch_uptake_by_paper_Top_Roll__g/m2_',
 'Starch_uptake_by_paper_Bottom_Roll__g/m2_',
 'Pressure_of_Starch_flow_Speedsizer_Bottom_Roll~^0',
 'Starch_consumption_Bottom___m³/h_',
 'Starch_consumption_Top__m³/h_',
 'Consistency_starch_main_line',
 'Pressure_of_Starch_flow_Speedsizer_Top_Roll',
 'Flow_starch_main_line_to_working_tank_2~^0',
 'Flow_starch_main_line_to_working_tank_1~^0',
 'Starch_Top_Roll__ml/m²_',
 'Starch_Bottom_Roll__ml/m²_',
 'Steam_flow_to_starch_kitchen',
 'Starch_flow_to_inactivation',
 'Pressure_starch_main_line',
 'Temperature_starch_working_tank_1',
 'Temperature_starch_working_tank_2',
 'Starch_application_FW_in_ml',
 'Starch_application_BW_in_ml',
 'Starch_mass_flow__kg/T_',
 'Starch__€/T_',
 'Starch_uptake__g/m2_',
 'ratio_starch',
 'Starch_current__€/h_',
 'Flow_starch_main_line_to_working_tank',
 'concentration_starch_working_tank_1',
 'concentration_starch_working_tank_2']

In [92]:
import importlib
import process_data_tools as pdt
import scenario_tools as st
 
importlib.reload(pdt)
importlib.reload(st)
 
# 1. Load full turnup dataset
df_all = pdt.load_turnup_data()
 
# 2. (Optional but recommended) filter before scenario
df = df_all[df_all["AB_Grade_ID"] == "6010120"]
 
# 3. Select reference turnup
ref = st.get_reference_turnup(
    df,
    grade="6010120"
)
 
# 4. Inspect result
print(st.describe_reference_turnup(ref))
print(ref["row"][["MBS_Current_reel_ID", "AB_Grade_ID", "Wedge_Time"]])

Selection mode: grade_latest
Matched reel: 12601970
Matched grade: 6010120
Matched time: 2026-03-16 06:51:00
Requested grade: 6010120
  MBS_Current_reel_ID AB_Grade_ID           Wedge_Time
0            12601970     6010120  2026-03-16 06:51:00

In [96]:
import importlib
import process_data_tools as pdt
import scenario_tools as st
 
importlib.reload(pdt)
importlib.reload(st)
 
# 1. Load data
df_all = pdt.load_turnup_data()
 
# 2. Get reference turnup
ref = st.get_reference_turnup(
    df_all,
    grade="6010120",
    schema={
        "reel_id": "MBS_Current_reel_ID",
        "grade": "AB_Grade_ID",
        "time": "Wedge_Time",
    }
)
 
# 3. Apply intervention
mod = st.apply_interventions(
    ref["row"],
    interventions=[
        {
            "variable": "Starch_uptake__g/m2_",
            "mode": "relative",   # try also "delta" or "absolute"
            "value": -0.10        # reduce by 10%
        }
    ]
)
 
# 4. Compare
var = "Starch_uptake__g/m2_"
 
print("REFERENCE VALUE:")
print(ref["row"][var].values[0])
 
print("\nMODIFIED VALUE:")
print(mod["row"][var].values[0])
 
print("\nAPPLIED INTERVENTIONS:")
print(mod["applied_interventions"])
 
print("\nWARNINGS:")
print(mod["warnings"])

REFERENCE VALUE:
5.784336

MODIFIED VALUE:
5.205902481079102

APPLIED INTERVENTIONS:
[{'variable': 'Starch_uptake__g/m2_', 'mode': 'relative', 'value': -0.1, 'old_value': 5.784336090087891, 'new_value': 5.205902481079102}]

WARNINGS:
[]

In [106]:
import importlib
import scenario_tools as st
 
importlib.reload(st)
 
sim = st.simulate_turnup_scenario(
    cost_component="steam",
    grade="6010120",
    interventions=[
        {
            "variable": 'Moisture_out_of_PreDryer',
            "mode": "absolute",
            "value": 7.28,
        }
    ],
)
 
print(st.describe_scenario_result(sim, decimals=10))

Cost component: steam
Baseline prediction: 886.4490742108
Scenario prediction: 875.5287324887
Delta prediction: -10.9203417221
Reference mode: grade_latest
Matched reel: 12601970
Matched grade: 6010120
Matched time: 2026-03-16 06:51:00
Intervention - Moisture_out_of_PreDryer: 9.1100425720 -> 7.2800000000 (mode=absolute, value=7.28)

In [119]:
import importlib
import assistant_router as ar
import query_parser as qp
import scenario_tools as st
 
importlib.reload(qp)
importlib.reload(st)
importlib.reload(ar)
 
q = "simulate electricity cost for grade 6010120 if Speed is increased by 10%"
 
parsed = qp.parse_query(q)
print(parsed)
 
out = ar.answer_scenario(
    cost_component=parsed.get("cost_component"),
    grade=parsed.get("grade"),
    reel_id=parsed.get("reel_id"),
    timestamp=parsed.get("timestamp"),
    target_range=parsed.get("target_range"),
    interventions=parsed.get("interventions"),
)
 
print(out["text"])

{'intent': 'simulate_scenario', 'cost_component': 'electricity', 'grade': '6010120', 'reel_id': None, 'timestamp': None, 'target_range': None, 'baseline_range': None, 'interventions': [{'variable': 'Speed', 'mode': 'delta', 'value': 10.0}], 'raw_query': 'simulate electricity cost for grade 6010120 if Speed is increased by 10%'}
Cost component: electricity
Baseline prediction: 291.5015
Scenario prediction: 290.4741
Delta prediction: -1.0274
Reference mode: grade_latest
Matched reel: 12601970
Matched grade: 6010120
Matched time: 2026-03-16 06:51:00
Intervention - Speed: 1253.9000 -> 1263.9000 (mode=delta, value=10.0)

In [109]:
out = ar.answer("simulate steam cost for grade 6010120 if Moisture_out_of_PreDryer is reduced by 10%")
print(out["text"] if isinstance(out, dict) and "text" in out else out)

Cost component: steam
Baseline prediction: 886.4491
Scenario prediction: 826.7765
Delta prediction: -59.6726
Reference mode: grade_latest
Matched reel: 12601970
Matched grade: 6010120
Matched time: 2026-03-16 06:51:00
Intervention - Moisture_out_of_PreDryer: 9.1100 -> -0.8900 (mode=delta, value=-10.0)

In [122]:
from datetime import date
import diagnosis_tools as diag

importlib.reload(diag)

In [125]:
from datetime import date
import diagnosis_tools as diag

importlib.reload(diag)
 

out = diag.run_diagnosis(
    target_range=(date(2026, 3, 1), date(2026, 3, 10)),
    baseline_range=(date(2026, 2, 1), date(2026, 3, 1)),
    objects="cost",
    levels=[1, 2, 3],
    grades=[6010120, 6010100],
)

print(out["combined_text"])
 
for block in out["blocks"]:
    print(block["level"], block["object_drilldown"])
    block["figure"].show()

For all considered grades, TOTAL cost saw a decrease of 1.65 €/t, resulting in 278.36 €/t.

Breaking down the overall cost change, 0.85 €/t was driven by a cheaper mix of grades, and 0.79 €/t was due to an improvement in the process.

For grade 6010100, TOTAL cost saw a decrease of 2.24 €/t, resulting in 284.21 €/t.

For grade 6010120, TOTAL cost saw a decrease of 0.46 €/t, resulting in 277.02 €/t.

Looking across individual grades, the strongest cost decrease was observed for grade 6010100 (-2.24 €/t). These movements stand out and may require further investigation.

Average change by component:

- **Steam__€/T_** decreased on average (-1.60 €/t).

- **Starch__€/T_** increased on average (+1.00 €/t).

- **Chemicals__€/T_** decreased on average (-0.35 €/t).

- **Fibre_cost__€/T_** decreased on average (-0.31 €/t).

- **Electricity__€/T_** decreased on average (-0.10 €/t).

A more detailed breakdown by component shows that the largest average increase comes from **Starch__€/T_** (+1.00 €/t on average), with the highest increase in grade 6010120 (+1.31 €/t) and the largest average decrease comes from **Steam__€/T_** (-1.60 €/t on average), with the biggest drop in grade 6010100 (-3.00 €/t). These components stand out and may require further investigation.
1 cost

2 cost

3 cost

In [126]:
import importlib
import query_parser as qp
import assistant_router as ar
 
importlib.reload(qp)
importlib.reload(ar)
 
q = "diagnose cost overall for grade 6010120 in March 2026"
parsed = qp.parse_query(q)
print(parsed)
 
out = ar.answer_diagnosis(
    target_range=parsed.get("target_range"),
    baseline_range=parsed.get("baseline_range"),
    grades=parsed.get("grades"),
    levels=parsed.get("levels"),
    objects=parsed.get("objects"),
    lang="en",
)
 
print(out["text"])

{'intent': 'diagnosis', 'cost_component': None, 'grade': '6010120', 'reel_id': None, 'timestamp': None, 'target_range': (datetime.date(2026, 3, 1), datetime.date(2026, 4, 1)), 'baseline_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'interventions': [], 'raw_query': 'diagnose cost overall for grade 6010120 in March 2026', 'levels': [1], 'objects': ['cost']}
For all considered grades, TOTAL cost saw a decrease of 1.04 €/t, resulting in 279.62 €/t.

Breaking down the overall cost change, 0.41 €/t was driven by a cheaper mix of grades, and 0.63 €/t was due to an improvement in the process.

In [129]:
import importlib
import query_parser as qp
import assistant_router as ar
 
importlib.reload(qp)
importlib.reload(ar)
 
out = ar.answer("diagnose cost by grade for grade 6010120 in March 2026")
print(out["text"])

For grade 3200115, TOTAL cost saw an increase of 1.33 €/t, resulting in 277.14 €/t.

For grade 6010085, TOTAL cost saw an increase of 1.77 €/t, resulting in 291.42 €/t.

For grade 6010100, TOTAL cost saw a decrease of 2.86 €/t, resulting in 283.59 €/t.

For grade 6010120, TOTAL cost saw a decrease of 1.47 €/t, resulting in 276.00 €/t.

Looking across individual grades, the strongest cost increase was observed for grade 6010085 (+1.77 €/t) and the strongest cost decrease was observed for grade 6010100 (-2.86 €/t). These movements stand out and may require further investigation.

In [ ]:
import importlib
import assistant_router as ar
from datetime import date
 
importlib.reload(ar)
 
out = ar.answer_diagnosis_with_scenario(
    target_range=(date(2026, 3, 1), date(2026, 3, 10)),
    baseline_range=(date(2026, 2, 1), date(2026, 3, 1)),
    grades=["6010120"],
    levels=[1],
    objects=["cost"],
    lang="en",
    cost_component="starch",
    interventions=[
        {
            "variable": "Starch_uptake__g/m2_",
            "mode": "relative",
            "value": -0.10,
        }
    ],
)
 
print(out["text"])

In [132]:
import importlib
import query_parser as qp
import analysis_planner as ap
 
importlib.reload(qp)
importlib.reload(ap)
 
q = "diagnose cost overall for grade 6010120 in March 2026"
parsed = qp.parse_query(q)
 
out = ap.make_plan(parsed, raw_query=q)
 
print(out["planning_context"]["allowed_tools"])
print(out["plan"])

['diagnosis', 'cost_driver', 'shap']
{'goal': 'diagnose', 'steps': [{'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 1), datetime.date(2026, 4, 1)), 'baseline_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'grades': ['6010120'], 'levels': [1], 'objects': ['cost'], 'lang': 'en'}}], 'final_template': 'diagnosis_only'}

In [133]:
import importlib

import query_parser as qp

import analysis_planner as ap

import analysis_executor as ae
 
importlib.reload(qp)

importlib.reload(ap)

importlib.reload(ae)
 
q = "diagnose cost overall for grade 6010120 in March 2026"
 
parsed = qp.parse_query(q)

plan_bundle = ap.make_plan(parsed, raw_query=q)

execution_out = ae.execute_plan(plan_bundle)
 
print(execution_out["plan"])

print("----")

for step in execution_out["step_results"]:

    print(step["tool"])

    if isinstance(step["result"], dict) and "text" in step["result"]:

        print(step["result"]["text"][:1000])

{'goal': 'diagnose', 'steps': [{'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 1), datetime.date(2026, 4, 1)), 'baseline_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'grades': ['6010120'], 'levels': [1], 'objects': ['cost'], 'lang': 'en'}}], 'final_template': 'diagnosis_only'}
----
diagnosis
For all considered grades, TOTAL cost saw a decrease of 1.47 €/t, resulting in 276.00 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 1.47 €/t was due to an improvement in the process.

In [134]:
import importlib
import query_parser as qp
import analysis_planner as ap
import analysis_executor as ae
import analysis_synthesizer as syn
 
importlib.reload(qp)
importlib.reload(ap)
importlib.reload(ae)
importlib.reload(syn)
 
q = "diagnose cost overall for grade 6010120 in March 2026"
 
parsed = qp.parse_query(q)
plan_bundle = ap.make_plan(parsed, raw_query=q)
execution_out = ae.execute_plan(plan_bundle)
final_out = syn.synthesize_execution(execution_out)
 
print(final_out["plan"])
print("-----")
print(final_out["text"])

{'goal': 'diagnose', 'steps': [{'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 1), datetime.date(2026, 4, 1)), 'baseline_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'grades': ['6010120'], 'levels': [1], 'objects': ['cost'], 'lang': 'en'}}], 'final_template': 'diagnosis_only'}
-----
For all considered grades, TOTAL cost saw a decrease of 1.47 €/t, resulting in 276.00 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 1.47 €/t was due to an improvement in the process.

In [135]:
import importlib
import query_parser as qp
import assistant_router as ar
 
importlib.reload(qp)
importlib.reload(ar)
 

out = ar.answer_orchestrated("diagnose cost overall for grade 6010120 in March 2026")
print(out["text"])

For all considered grades, TOTAL cost saw a decrease of 1.47 €/t, resulting in 276.00 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 1.47 €/t was due to an improvement in the process.

In [136]:
import importlib
import assistant_router as ar
importlib.reload(ar)
out = ar.answer("diagnose cost overall for grade 6010120 in March 2026")
print(out["text"])
print(out["plan"])

For all considered grades, TOTAL cost saw a decrease of 1.47 €/t, resulting in 276.00 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 1.47 €/t was due to an improvement in the process.
{'goal': 'diagnose', 'steps': [{'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 1), datetime.date(2026, 4, 1)), 'baseline_range': (datetime.date(2026, 2, 1), datetime.date(2026, 3, 1)), 'grades': ['6010120'], 'levels': [1], 'objects': ['cost'], 'lang': 'en'}}], 'final_template': 'diagnosis_only'}

In [147]:
import importlib
import query_parser as qp
import analysis_planner as ap
import analysis_executor as ae
import analysis_synthesizer as syn
 
importlib.reload(qp)
importlib.reload(ap)

parsed = qp.parse_query(
    "what are the recommendations to improve the steam cost for grade 6010120 in week 11"
)
print(parsed)
plan_bundle = ap.make_plan(
    parsed,
    raw_query="what are the recommendations to improve the steam cost for grade 6010120 in week 11"
)
print(plan_bundle["planning_context"]["allowed_tools"])
print(plan_bundle["planning_context"]["context_signals"])
print(plan_bundle["plan"])

{'intent': 'diagnosis', 'cost_component': 'steam', 'grade': '6010120', 'reel_id': None, 'timestamp': None, 'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'interventions': [], 'raw_query': 'what are the recommendations to improve the steam cost for grade 6010120 in week 11', 'levels': None, 'objects': ['cost']}
['diagnosis', 'cost_driver', 'shap', 'recommend']
{'wants_explanation': False, 'wants_recommendations': True, 'wants_estimate': False, 'wants_simulation': False}
{'goal': 'recommend', 'steps': [{'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'grades': ['6010120'], 'objects': ['cost'], 'lang': 'en'}}, {'tool': 'cost_driver', 'purpose': 'Identify the variables contributing to the change between periods.', 'args': {'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'grade': '6010120', 'cost_component': 'steam'}}, {'tool': 'recommend', 'purpose': 'Generate actionable recommendations based on diagnosis and drivers.', 'args': {'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'grade': '6010120', 'cost_component': 'steam', 'lang': 'en'}}], 'final_template': 'diagnosis_plus_cost_driver_plus_recommendations'}

In [149]:
import cost_driver_tools as cdt
import analysis_executor as ae

importlib.reload(cdt)
importlib.reload(ae)

out = cdt.run_cost_driver_analysis(
    target_range=(pd.to_datetime("2026-03-09").date(), pd.to_datetime("2026-03-14").date()),
    baseline_range=(pd.to_datetime("2026-02-09").date(), pd.to_datetime("2026-03-09").date()),
    cost_component="steam",
    grade="6010120",
)
print(type(out))
print(out.keys())
print(out["process_data_clustered"] is None)
print(out["df1"].shape if out["df1"] is not None else None)
print(out["df2"].shape if out["df2"] is not None else None)
print(out["shapley_contrib"].shape if out["shapley_contrib"] is not None else None)

['historic' 'current']
<class 'dict'>
dict_keys(['cost_component', 'cost_component_full_name', 'grade', 'target_range', 'baseline_range', 'process_data_clustered', 'df1', 'df2', 'shapley_contrib', 'top_driver_variables', 'extreme_cluster_differences'])
False
(19, 27)
(18, 27)
(24, 4)

In [150]:
import analysis_executor as ae

importlib.reload(ae)


execution_out = ae.execute_plan(plan_bundle)
 
for step in execution_out["step_results"]:
    print(step["tool"])
    print(type(step["result"]))
    print(step["result"])
    print("-----")

['historic' 'current']
diagnosis
<class 'dict'>
{'text': 'For all considered grades, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.\n\nBreaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 2.53 €/t was due to an improvement in the process.\n\nFor grade 6010120, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.\n\nAverage change by component:\n\n- **Steam__€/T_** decreased on average (-2.59 €/t).\n\n- **Starch__€/T_** increased on average (+1.47 €/t).\n\n- **Electricity__€/T_** decreased on average (-0.50 €/t).\n\n- **Chemicals__€/T_** decreased on average (-0.48 €/t).\n\n- **Fibre_cost__€/T_** decreased on average (-0.44 €/t).\n\nA more detailed breakdown by component shows that the largest average increase comes from **Starch__€/T_** (+1.47 €/t on average), with the highest increase in grade 6010120 (+1.47 €/t) and the largest average decrease comes from **Steam__€/T_** (-2.59 €/t on average), with the biggest drop in grade 6010120 (-2.59 €/t). These components stand out and may require further investigation.', 'data': {'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'grades_summary': ['6010120'], 'levels': [1, 2, 3], 'objects': ['cost'], 'lang': 'en', 'reference': 'baseline', 'process_data':               Wedge_Time  MBS_SCT_MD  MBS_SCT_CD   MBS_Burst   MBS_CMT30  \
2800 2026-02-09 15:31:00        4.62        2.43  297.910004  193.159073
2801 2026-02-10 00:41:00        3.98        2.13  289.170013  192.000000
2802 2026-02-10 02:03:00        3.98        2.08  281.519989  197.000000
2803 2026-02-11 01:24:00        4.09        2.13  286.429993  194.000000
2804 2026-02-11 02:36:00        3.98        2.12  285.959991  194.000000
...                  ...         ...         ...         ...         ...
3216 2026-03-11 12:21:00        3.92        2.14  285.299988  190.000000
3217 2026-03-11 13:07:00        4.01        2.16  280.130005  190.000000
3218 2026-03-11 13:53:00        3.97        2.18  281.470001  190.000000
3219 2026-03-11 14:40:00        4.01        2.28  290.679993  190.000000
3220 2026-03-11 15:49:00        4.01        2.20  292.549988  190.000000

      MBS_Current_reel_ID AB_Grade_ID  Stock_pump_power        Speed  \
2800             12601011     6010120        815.900024  1190.500000
2801             12601022     6010120        816.500000  1190.699951
2802             12601024     6010120        813.100037  1190.800049
2803             12601029     6010120        707.799988  1085.849976
2804             12601030     6010120        717.400024  1094.699951
...                   ...         ...               ...          ...
3216             12601837     6010120        884.200012  1280.300049
3217             12601838     6010120        884.400024  1280.199951
3218             12601839     6010120        887.500000  1279.900024
3219             12601840     6010120        887.400024  1279.699951
3220             12601842     6010120        884.900024  1280.000000

      Current_reel_width  ...  Electricity_sqm  SCT_CD_index  retention  \
2800          755.400024  ...         0.036167      0.020591   0.834700
2801          755.250000  ...         0.035195      0.018052   0.817215
2802          755.700012  ...         0.027542      0.017580   0.816081
2803          757.599976  ...         0.036718      0.017871   0.865132
2804          757.700012  ...         0.036561      0.017855   0.865667
...                  ...  ...              ...           ...        ...
3216          755.000000  ...         0.034407      0.017875   0.781317
3217          754.949951  ...         0.034877      0.018393   0.788529
3218          754.849976  ...         0.034970      0.018398   0.787916
3219          754.500000  ...         0.033671      0.019319   0.774926
3220          755.200012  ...         0.033626      0.018507   0.787808

      Wedge_Date  Overprocessing_percentage  Overprocessing_SCT_CD  \
2800  2026-02-09                   0.114734               0.185366
2801  2026-02-10                   0.038431               0.039024
2802  2026-02-10                   0.039749               0.014634
2803  2026-02-11                   0.043837               0.039024
2804  2026-02-11                   0.041397               0.034146
...          ...                        ...                    ...
3216  2026-03-11                   0.035465               0.043902
3217  2026-03-11                   0.040343               0.053659
3218  2026-03-11                   0.045221               0.063415
3219  2026-03-11                   0.069611               0.112195
3220  2026-03-11                   0.050099               0.073171

      Overprocessing_Burst  Overprocessing_CMT30  Overprocessing_cost__€/T_  \
2800                   NaN              0.044103                  55.676927
2801                   NaN              0.037838                  47.702600
2802                   NaN              0.064865                  81.521427
2803                   NaN              0.048649                  60.710505
2804                   NaN              0.048649                  60.940400
...                    ...                   ...                        ...
3216                   NaN              0.027027                  33.591665
3217                   NaN              0.027027                  34.250109
3218                   NaN              0.027027                  33.951580
3219                   NaN              0.027027                  34.116732
3220                   NaN              0.027027                  33.848598

        target
2800  historic
2801  historic
2802  historic
2803  historic
2804  historic
...        ...
3216   current
3217   current
3218   current
3219   current
3220   current

[170 rows x 470 columns], 'blocks': [{'level': 1, 'object_drilldown': 'cost', 'reference': 'baseline', 'drilldown':     target  current_cost   n   cost  previous_cost AB_Grade_ID  pct_cost
0  current    274.554199  35  TOTAL     277.087128         ALL -2.532928, 'mix_contribution': (np.float64(0.0), np.float64(-2.532928466796875)), 'description_md': 'For all considered grades, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.\n\nBreaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 2.53 €/t was due to an improvement in the process.', 'figure': Figure({
    'data': [{'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-2.5€/t', 277.0871276855469, -2.532928466796875, 274.55419921875]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-2.5329285], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['274.55 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['ALL'], dtype=object),
              'xaxis': 'x',
              'y': array([274.5542], dtype=float32),
              'yaxis': 'y'},
             {'cliponaxis': False,
              'hoverinfo': 'skip',
              'mode': 'text',
              'showlegend': False,
              'text': [▼-2.5€/t (Mix • 0, Process ▼ -2.5 €/t)],
              'textfont': {'color': ['#2ca02c'], 'size': 11},
              'textposition': 'top center',
              'type': 'scatter',
              'x': array(['ALL'], dtype=object),
              'xaxis': 'x',
              'y': [282.7908251953125],
              'yaxis': 'y'}],
    'layout': {'annotations': [{'font': {},
                                'showarrow': False,
                                'text': 'cost=TOTAL',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'autosize': True,
               'barmode': 'relative',
               'coloraxis': {'cmax': 2.532928466796875,
                             'cmin': -2.532928466796875,
                             'colorbar': {'title': {'text': 'Current cost (€/t)'}},
                             'colorscale': [[0.0, '#ccffcc'], [0.5, '#ffffff'],
                                            [1.0, '#ffcccc']],
                             'showscale': False},
               'font': {'color': '#222', 'size': 12},
               'height': 450.0,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 40, 'l': 50, 'r': 20, 't': 70},
               'paper_bgcolor': 'white',
               'plot_bgcolor': 'white',
               'template': '...',
               'title': {'text': ''},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'gridcolor': 'rgba(200,200,200,0.4)',
                         'showgrid': True,
                         'tickangle': 0,
                         'title': {'text': 'AB_Grade_ID'},
                         'zeroline': False},
               'yaxis': {'anchor': 'x',
                         'automargin': True,
                         'domain': [0.0, 1.0],
                         'gridcolor': 'rgba(200,200,200,0.4)',
                         'showgrid': True,
                         'title': {'text': 'Current cost (€/t)'},
                         'zeroline': False}}
})}, {'level': 2, 'object_drilldown': 'cost', 'reference': 'baseline', 'drilldown':     target AB_Grade_ID  current_cost   n   cost  previous_cost  pct_cost
0  current     6010120    274.554199  35  TOTAL     277.087128 -2.532928, 'mix_contribution': None, 'description_md': 'For grade 6010120, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.', 'figure': Figure({
    'data': [{'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-2.5€/t', 277.0871276855469, -2.532928466796875, 274.55419921875]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-2.5329285], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['274.55 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x',
              'y': array([274.5542], dtype=float32),
              'yaxis': 'y'},
             {'cliponaxis': False,
              'hoverinfo': 'skip',
              'mode': 'text',
              'showlegend': False,
              'text': [▼-2.5€/t],
              'textfont': {'color': ['#2ca02c'], 'size': 11},
              'textposition': 'top center',
              'type': 'scatter',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x',
              'y': [282.7908251953125],
              'yaxis': 'y'}],
    'layout': {'annotations': [{'font': {},
                                'showarrow': False,
                                'text': 'cost=TOTAL',
                                'x': 0.5,
                                'xanchor': 'center',
                                'xref': 'paper',
                                'y': 1.0,
                                'yanchor': 'bottom',
                                'yref': 'paper'}],
               'autosize': True,
               'barmode': 'relative',
               'coloraxis': {'cmax': 2.532928466796875,
                             'cmin': -2.532928466796875,
                             'colorbar': {'title': {'text': 'Current cost (€/t)'}},
                             'colorscale': [[0.0, '#ccffcc'], [0.5, '#ffffff'],
                                            [1.0, '#ffcccc']],
                             'showscale': False},
               'font': {'color': '#222', 'size': 12},
               'height': 450.0,
               'legend': {'tracegroupgap': 0},
               'margin': {'b': 40, 'l': 50, 'r': 20, 't': 70},
               'paper_bgcolor': 'white',
               'plot_bgcolor': 'white',
               'template': '...',
               'title': {'text': ''},
               'xaxis': {'anchor': 'y',
                         'domain': [0.0, 1.0],
                         'gridcolor': 'rgba(200,200,200,0.4)',
                         'showgrid': True,
                         'tickangle': 0,
                         'title': {'text': 'AB_Grade_ID'},
                         'zeroline': False},
               'yaxis': {'anchor': 'x',
                         'automargin': True,
                         'domain': [0.0, 1.0],
                         'gridcolor': 'rgba(200,200,200,0.4)',
                         'showgrid': True,
                         'title': {'text': 'Current cost (€/t)'},
                         'zeroline': False}}
})}, {'level': 3, 'object_drilldown': 'cost', 'reference': 'baseline', 'drilldown':     target AB_Grade_ID  current_cost   n               cost  previous_cost  \
0  current     6010120    274.554199  35              TOTAL     277.087128
1  current     6010120      3.770386  35    Chemicals__€/T_       4.245947
2  current     6010120     32.468616  35  Electricity__€/T_      32.970142
3  current     6010120    127.251663  35   Fibre_cost__€/T_     127.687454
4  current     6010120     24.094885  35       Starch__€/T_      22.626038
5  current     6010120     86.968628  35        Steam__€/T_      89.557541

   pct_cost
0 -2.532928
1 -0.475562
2 -0.501526
3 -0.435791
4  1.468847
5 -2.588913  , 'mix_contribution': None, 'description_md': 'Average change by component:\n\n- **Steam__€/T_** decreased on average (-2.59 €/t).\n\n- **Starch__€/T_** increased on average (+1.47 €/t).\n\n- **Electricity__€/T_** decreased on average (-0.50 €/t).\n\n- **Chemicals__€/T_** decreased on average (-0.48 €/t).\n\n- **Fibre_cost__€/T_** decreased on average (-0.44 €/t).\n\nA more detailed breakdown by component shows that the largest average increase comes from **Starch__€/T_** (+1.47 €/t on average), with the highest increase in grade 6010120 (+1.47 €/t) and the largest average decrease comes from **Steam__€/T_** (-2.59 €/t on average), with the biggest drop in grade 6010120 (-2.59 €/t). These components stand out and may require further investigation.', 'figure': Figure({
    'data': [{'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-2.5€/t', 277.0871276855469, -2.532928466796875, 274.55419921875]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-2.5329285], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['274.55 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x4',
              'y': array([274.5542], dtype=float32),
              'yaxis': 'y4'},
             {'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-0.4€/t', 127.68745422363281, -0.435791015625, 127.25166320800781]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-0.43579102], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['127.25 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x5',
              'y': array([127.25166], dtype=float32),
              'yaxis': 'y5'},
             {'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-2.6€/t', 89.55754089355469, -2.5889129638671875, 86.9686279296875]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-2.588913], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['86.97 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x6',
              'y': array([86.96863], dtype=float32),
              'yaxis': 'y6'},
             {'alignmentgroup': 'True',
              'cliponaxis': False,
              'customdata': array([['▼-0.5€/t', 32.97014236450195, -0.50152587890625, 32.4686164855957]],
                                  dtype=object),
              'hovertemplate': ('<b>%{facetcol} • ID %{x}</b><b' ... 'omdata[2]:.2%}}<extra></extra>'),
              'insidetextanchor': 'middle',
              'legendgroup': '',
              'marker': {'color': array([-0.5015259], dtype=float32),
                         'coloraxis': 'coloraxis',
                         'line': {'color': 'rgba(60,60,60,0.5)', 'width': 0.8},
                         'pattern': {'shape': ''}},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'text': array(['32.47 €/t'], dtype=object),
              'textfont': {'color': 'black', 'size': 11},
              'textposition': 'inside',
              'type': 'bar',
              'x': array(['6010120'], dtype=object),
              'xaxis': 'x',
              'y': array([32.468616], dtype=float32),

In [142]:
import importlib
import assistant_router as ar
 
importlib.reload(ar)
 
out = ar.answer(
    "what are the recommendations to improve the steam cost for grade 6010120 in week 11"
)
 
print(out["text"])
print(out["plan"])

Knowledge context

{'type': 'knowledge', 'answer': 'I appreciate your question, but I need to inform you that **the provided context does not contain any information about grade 6010120 or week 11 specific data**.\n\nThe context provided includes general papermaking engineering content covering:\n- Steam system design and control concepts\n- Energy efficiency principles for evaporation systems\n- Grade change procedures\n- Steam pressure and temperature recommendations\n- Benchmarking data for various paper grades (newsprint, SC, LWC, etc.)\n\n## What I Would Need to Answer Your Question:\n\nTo provide specific recommendations for improving steam cost for grade 6010120 in week 11, I would need:\n\n1. **Actual performance data** for grade 6010120 in week 11 (steam consumption, production rate, moisture profiles)\n2. **Historical baseline data** for this grade\n3. **Plant-specific operating conditions** and equipment configuration\n4. **Grade specifications** and quality requirements\n5. **Cost structure** for steam at your facility\n\n## General Recommendations (Based on Context):\n\nWhile I cannot provide plant-specific guidance, the context does suggest these general principles for steam cost optimization:\n\n1. **Use low-pressure steam** (0.2-0.5 MPa) when possible for better energy efficiency due to higher condensing heat rates [papermaking_science_technology.pdf:d6f6f20ccb65b658:4651:0]\n\n2. **Optimize steam pressure control** during grade runs to minimize variations (±10 kPa during 10-minute periods) [papermaking_science_technology.pdf:d6f6f20ccb65b658:4651:0]\n\n3. **Review grade change procedures** as these significantly impact steam consumption [papermaking_science_technology.pdf:d6f6f20ccb65b658:4602:0]\n\n**Please provide the specific operational data for grade 6010120 in week 11 for targeted recommendations.**', 'sources': [{'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:3036:0', 'file': 'papermaking_science_technology.pdf', 'page': 3036, 'chunk': None, 'score': 0.3788919448852539, 'row_id': 3669}, {'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:4602:0', 'file': 'papermaking_science_technology.pdf', 'page': 4602, 'chunk': None, 'score': 0.37038713693618774, 'row_id': 5319}, {'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:4651:0', 'file': 'papermaking_science_technology.pdf', 'page': 4651, 'chunk': None, 'score': 0.36771246790885925, 'row_id': 5369}, {'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:4578:0', 'file': 'papermaking_science_technology.pdf', 'page': 4578, 'chunk': None, 'score': 0.36421293020248413, 'row_id': 5293}, {'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:4650:0', 'file': 'papermaking_science_technology.pdf', 'page': 4650, 'chunk': None, 'score': 0.35245802998542786, 'row_id': 5368}, {'id': 'papermaking_science_technology.pdf:d6f6f20ccb65b658:4629:0', 'file': 'papermaking_science_technology.pdf', 'page': 4629, 'chunk': None, 'score': 0.3412505090236664, 'row_id': 5346}]}

---

Analysis

For all considered grades, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 2.53 €/t was due to an improvement in the process.

For all considered grades, TOTAL overprocessing saw an increase of 1.06 %, resulting in 5.10 %.

For grade 6010120, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.

For grade 6010120, TOTAL overprocessing saw an increase of 1.06 %, resulting in 5.10 %.

Average change by component:

- **Steam__€/T_** decreased on average (-2.59 €/t).

- **Starch__€/T_** increased on average (+1.47 €/t).

- **Electricity__€/T_** decreased on average (-0.50 €/t).

- **Chemicals__€/T_** decreased on average (-0.48 €/t).

- **Fibre_cost__€/T_** decreased on average (-0.44 €/t).

A more detailed breakdown by component shows that the largest average increase comes from **Starch__€/T_** (+1.47 €/t on average), with the highest increase in grade 6010120 (+1.47 €/t) and the largest average decrease comes from **Steam__€/T_** (-2.59 €/t on average), with the biggest drop in grade 6010120 (-2.59 €/t). These components stand out and may require further investigation.

Average change by component:

- **SCT_CD** increased on average (+1.51 %).

- **CMT30** increased on average (+0.62 %).

A more detailed breakdown by component shows that the largest average increase comes from **SCT_CD** (+1.51 % on average), with the highest increase in grade 6010120 (+1.51 %). These components stand out and may require further investigation.
{'goal': 'knowledge_assisted_analysis', 'steps': [{'tool': 'knowledge', 'purpose': 'Retrieve relevant knowledge context.', 'args': {'query': 'what are the recommendations to improve the steam cost for grade 6010120 in week 11'}}, {'tool': 'diagnosis', 'purpose': 'Diagnose the issue across the requested drilldown levels and objects.', 'args': {'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'grades': ['6010120'], 'lang': 'en'}}], 'final_template': 'knowledge_plus_analysis'}

In [155]:
import importlib
import analysis_planner as ap
import analysis_executor as ae
import analysis_synthesizer as asy
import recommendation_tools as rt
import cost_driver_tools as cdt
import assistant_router as ar

def reload_all():
    
    importlib.reload(ap)
    importlib.reload(ae)
    importlib.reload(asy)
    importlib.reload(rt)
    importlib.reload(cdt)
    importlib.reload(ar)

In [158]:
reload_all()
out = ar.answer("what are the recommendations to improve the steam cost for grade 6010120 in week 11")
print(out["text"])

['historic' 'current']
For all considered grades, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.

Breaking down the overall cost change, 0.00 €/t was driven by a unchanged mix of grades, and 2.53 €/t was due to an improvement in the process.

For grade 6010120, TOTAL cost saw a decrease of 2.53 €/t, resulting in 274.55 €/t.

Average change by component:

- **Steam__€/T_** decreased on average (-2.59 €/t).

- **Starch__€/T_** increased on average (+1.47 €/t).

- **Electricity__€/T_** decreased on average (-0.50 €/t).

- **Chemicals__€/T_** decreased on average (-0.48 €/t).

- **Fibre_cost__€/T_** decreased on average (-0.44 €/t).

A more detailed breakdown by component shows that the largest average increase comes from **Starch__€/T_** (+1.47 €/t on average), with the highest increase in grade 6010120 (+1.47 €/t) and the largest average decrease comes from **Steam__€/T_** (-2.59 €/t on average), with the biggest drop in grade 6010120 (-2.59 €/t). These components stand out and may require further investigation.

---

Main contributing drivers

{'type': 'cost_driver_analysis', 'component': 'steam', 'grade': '6010120', 'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'used_default_ranges': False, 'n_rows': 24, 'raw': {'cost_component': 'steam', 'cost_component_full_name': 'Steam__€/T_', 'grade': '6010120', 'target_range': (datetime.date(2026, 3, 9), datetime.date(2026, 3, 14)), 'baseline_range': (datetime.date(2026, 2, 9), datetime.date(2026, 3, 9)), 'process_data_clustered':       Moisture_out_of_PreDryer  concentration_starch_working_tank_2  \
2800                  8.932500                             0.605279
2801                  9.062861                             0.610103
2802                  8.826099                             0.593235
2803                  8.609319                             0.603565
2804                  8.973950                             0.597227
...                        ...                                  ...
3216                  9.107089                             0.588369
3217                  9.021131                             0.580642
3218                  9.197762                             0.586665
3219                  8.897855                             0.576545
3220                  8.852948                             0.574140

      Steam_temperature_for_PM  Starch_uptake_by_paper_Top_Roll__g/m2_  \
2800                165.971893                                2.238691
2801                165.690094                                1.923739
2802                166.285538                                1.935657
2803                168.142365                                2.000901
2804                168.147766                                1.972166
...                        ...                                     ...
3216                167.621521                                1.901449
3217                167.274445                                1.871251
3218                167.103424                                1.897180
3219                167.197021                                1.881787
3220                167.708359                                1.870027

      Vacuum_wire_suction_box_2  Current_basis_weight  PD2_Fabric_tension  \
2800                  -0.555845            118.010635            4.016666
2801                  -0.566117            117.994957            4.075000
2802                  -0.567130            118.318352            4.100000
2803                  -0.520833            119.189842            4.250000
2804                  -0.500723            118.734596            3.923077
...                         ...                   ...                 ...
3216                  -0.577836            119.720131            3.900000
3217                  -0.568287            117.438515            4.000000
3218                  -0.570168            118.491257            3.991666
3219                  -0.564381            118.017822            3.950000
3220                  -0.571615            118.871948            3.950000

      Cylinder_38_differential_pressure  Vacuum_wet_suction_box  \
2800                           0.208033               -0.099596
2801                           0.186265               -0.099637
2802                           0.205175               -0.100313
2803                           0.214142               -0.099606
2804                           0.216622               -0.098729
...                                 ...                     ...
3216                           0.214040               -0.099306
3217                           0.210282               -0.099848
3218                           0.182308               -0.100213
3219                           0.185789               -0.098624
3220                           0.180154               -0.100868

      Current_reel_width  ...  Dissolved_gas_before_dilution_water_deculator  \
2800          755.400024  ...                                       0.993056
2801          755.250000  ...                                       1.425926
2802          755.700012  ...                                       1.324074
2803          757.599976  ...                                       0.914352
2804          757.700012  ...                                       0.692130
...                  ...  ...                                            ...
3216          755.000000  ...                                       1.865741
3217          754.949951  ...                                       1.784722
3218          754.849976  ...                                       1.805556
3219          754.500000  ...                                       1.715278
3220          755.200012  ...                                       1.854167

      Linepressure_shoe_press__bar_  Total_Dewatering_Press    Speed_PD1  \
2800                     101.598663             3066.883789  1172.800049
2801                     101.598663             3106.698730  1172.800049
2802                     101.526329             3127.669434  1172.900024
2803                     101.490166             4592.715820  1069.800049
2804                     101.598663             4576.344238  1078.400024
...                             ...                     ...          ...
3216                     101.634834             3281.654785  1259.900024
3217                     101.562500             3131.963867  1259.900024
3218                     101.526329             3243.778320  1259.800049
3219                     101.453995             3230.681396  1259.900024
3220                     101.707169             3268.282471  1259.900024

      Jet/wire_ratio  DG4_Temperature_Inlet_Air  Steam__€/T_  AB_Grade_ID  \
2800      -23.940002                 109.857491    94.859901      6010120
2801      -19.315002                 106.597229    96.126411      6010120
2802      -22.090002                 105.053658    99.043983      6010120
2803      -22.305002                 108.575340    95.917603      6010120
2804      -22.395002                 104.427071    94.020302      6010120
...              ...                        ...          ...          ...
3216      -15.685002                 112.640663    84.306122      6010120
3217      -16.170002                 110.937500    85.772728      6010120
3218      -15.840002                 111.260490    85.078087      6010120
3219      -16.115002                 110.503456    85.525719      6010120
3220      -16.200003                 110.644379    82.714737      6010120

        target  cluster
2800  historic        1
2801  historic        1
2802  historic        1
2803  historic        2
2804  historic        2
...        ...      ...
3216   current        2
3217   current        2
3218   current        2
3219   current        2
3220   current        2

[170 rows x 28 columns], 'df1':     Moisture_out_of_PreDryer  concentration_starch_working_tank_2  \
0                   9.161169                             0.654130
1                   8.967254                             0.605591
2                   9.149580                             0.579919
3                   8.909349                             0.585368
4                   9.074295                             0.585918
5                   9.145272                             0.582188
6                   8.896878                             0.581731
7                   9.048879                             0.569566
8                   9.022022                             0.585907
9                   8.899846                             0.571508
10                  9.019182                             0.585276
11                  9.143794                             0.587752
12                  8.997070                             0.582107
13                  9.181377                             0.585356
14                  9.154836                             0.575818
15                  9.143822                             0.585739
16                  9.151337                             0.582425
17                  8.978720                             0.579966
18                  9.156546                             0.580128

    Steam_temperature_for_PM  Starch_uptake_by_paper_Top_Roll__g/m2_  \
0                 164.006897                                2.542629
1                 168.402863                                2.383274
2                 167.274338                                1.896419
3                 167.806000                                1.858256
4                 166.840652                                1.890055
5                 167.447922                                1.850052
6                 167.621552                                1.837192
7                 167.534729                                1.861084
8                 167.447937                                1.862888
9                 167.708344                                1.845083
10                167.663757                                1.846343
11                167.631714                                1.867836
12                167.534744                                1.905978
13                167.708344                                1.939426
14                169.184052                                1.980178
15                167.282440                                1.964312
16                168.055389                                2.050541
17                167.708344                                2.184023
18                167.708344                                2.245715

    Vacuum_wire_suction_box_2  Current_basis_weight  PD2_Fabric_tension  \
0                   -0.551071            118.128281            3.850000
1                   -0.599392            114.385979            3.857143
2                   -0.575087            118.587448            3.900000
3                   -0.580585            118.574730            3.900000
4                   -0.580440            118.346680            4.000000
5                   -0.577546            119.226265            3.900000
6                   -0.577546            118.384132            3.960000
7                   -0.571904            118.569771            3.925000
8                   -0.576100            118.743782            3.925000
9                   -0.576100            118.628693            3.950000
10                  -0.572049            117.872353            3.900000
11                  -0.588252            118.696762            3.900000
12                  -0.586083            120.161003            4.100000
13                  -0.585069            118.829773            4.100000
14                  -0.589265            118.500946            4.007692
15                  -0.597222            119.071175            3.961538
16                  -0.595197            118.877487            4.000000
17                  -0.587819            119.293350            4.000000
18                  -0.586371            119.055603            4.100000

    Cylinder_38_differential_pressure  Vacuum_wet_suction_box  \
0                            0.185791               -0.099688
1                            0.188562               -0.100399
2                            0.198757               -0.098973
3                            0.184154               -0.098789
4                            0.194176               -0.100148
5                            0.197239               -0.101043
6                            0.186238               -0.099317
7                            0.211432               -0.098793
8                            0.194234               -0.098752
9                            0.176753               -0.099324
10                           0.191062               -0.100175
11                           0.201629               -0.099439
12                           0.207305               -0.102028
13                           0.196116               -0.098781
14                           0.202699               -0.099554
15                           0.197657               -0.098912
16                           0.198870               -0.099603
17                           0.210867               -0.099163
18                           0.192335               -0.098363

    Current_reel_width  ...  retention  \
0           755.650024  ...   0.809958
1           755.650024  ...   0.793356
2           753.849976  ...   0.792479
3           754.450012  ...   0.784134
4           754.349976  ...   0.778660
5           753.799988  ...   0.786502
6           753.549988  ...   0.775361
7           753.399963  ...   0.789783
8           753.349976  ...   0.790283
9           753.349976  ...   0.789005
10          754.000000  ...   0.788785
11          753.750000  ...   0.780193
12          754.549988  ...   0.784529
13          753.899963  ...   0.789279
14          754.050049  ...   0.778621
15          754.700012  ...   0.759835
16          754.000000  ...   0.772630
17          754.200012  ...   0.781835
18          754.349976  ...   0.796267

    Dissolved_gas_before_dilution_water_deculator  \
0                                        1.715278
1                                        1.576389
2                                        1.877315
3                                        1.925926
4                                        1.935185
5                                        1.965278
6                                        1.865741
7                                        1.854167
8                                        1.877315
9                                        1.886574
10                                       1.775463
11                                       1.837963
12                                       1.895833
13                                       1.796296
14                                       1.914352
15                                       1.914352
16                                       1.914352
17                                       1.914352
18                                       1.946759

    Linepressure_shoe_press__bar_  Total_Dewatering_Press    Speed_PD1  \
0                      101.562500             3196.306641  1211.000000
1                      101.598663             3236.775391  1233.500000
2                      101.381660             3352.010254  1260.400024
3                      101.671005             3358.490479  1260.400024
4                      101.381660             3246.305176  1260.400024
5                      101.671005             3221.747070  1260.400024
6                      101.562500             3224.784180  1260.500000
7                      101.417824             3279.806152  1260.500000
8                      101.526329             3196.494385  1260.400024
9                      101.417824             3208.940186  1260.500000
10                     101.562500             3206.285400  1260.400024
11                     101.381660             3246.131592  1260.500000
12                     101.417824             3301.477051  1260.400024
13                     101.598663             3265.151855  1260.400024
14                     101.598663             3267.628418  1260.400024
15                     101.634834             3234.954834  1260.400024
16                     101.598663             3248.382324  1260.400024
17                     101.490166             3287.719727  1260.400024
18                     101.562500             3204.876709  1260.500000

    Jet/wire_ratio  DG4_Temperature_Inlet_Air  AB_Grade_ID  Steam__€/T_  \
0       -29.230001                 111.935768      6010120    98.207352
1       -16.145002                 106.501678      6010120    91.469170
2       -23.075001                 111.289047      6010120    97.070290
3       -23.660002                 111.167686      6010120    97.085022
4       -23.470001                 111.546257      6010120    98.462967
5       -23.405001                 111.786240      6010120    99.609192
6       -28.425001                 110.983849      6010120    98.355705
7       -28.360003                 110.416542      6010120    99.800026
8       -29.495003                 110.495811      6010120    98.731148
9       -29.965002                 109.353256      6010120    98.032326
10      -29.485001                 108.614113      6010120    98.389877
11      -29.575001                 110.303925      6010120    96.884491
12      -28.670002                 109.824776      6010120    84.899673
13      -28.780003                 110.714996      6010120    86.990730
14      -27.980003                 111.138977      6010120    86.934700
15      -28.610003                 112.376846      6010120    88.050484
16      -28.285002                 112.461411      6010120    86.691353
17      -28.915003                 116.814606      6010120    87.769821
18      -28.330002                 117.257172      6010120    88.645744

       unknown
0  -909.868800
1  -983.521448
2  -916.467382
3  -832.817245
4  -913.268921
5  -822.707040
6  -878.036172
7  -884.283509
8  -909.744119
9  -942.401700
10 -885.641339
11 -921.928617
12 -848.611845
13 -877.967451
14 -879.089123
15 -891.597656
16 -868.498424
17 -937.541744
18 -973.501209

[19 rows x 27 columns], 'df2':     Moisture_out_of_PreDryer  concentration_starch_working_tank_2  \
0                   8.994809                             0.576356
1                   9.038703                             0.582134
2                   9.066659                             0.582065
3                   9.022571                             0.586010
4                   8.897885                             0.571918
5                   8.957037                             0.568575
6                   9.068702                             0.577435
7                   8.817751                             0.584556
8                   9.231126                             0.581141
9                   9.196939                             0.578071
10                  8.940476                             0.581301
11                  8.975898                             0.575678
12                  8.953147                             0.574644
13                  9.107089                             0.588369
14                  9.021131                             0.580642
15                  9.197762                             0.586665
16                  8.897855                             0.576545
17                  8.852948                             0.574140

    Steam_temperature_for_PM  Starch_uptake_by_paper_Top_Roll__g/m2_  \
0                 167.698135                                1.959530
1                 168.402771                                1.988384
2                 166.756149                                2.020860
3                 167.447937                                2.062687

# Test

In [ ]:
import importlib
import boto3
import traceback
from datetime import date
import pandas as pd
import query_parser as qp
import analysis_planner as ap
import analysis_executor as ae
import analysis_synthesizer as syn
import assistant_router as ar
import scenario_tools as st
import diagnosis_tools as diag
import cost_driver_tools as cdt
import recommendation_tools as rt
import process_data_tools as pdt
import analysis_test as at
modules = [qp, ap, ae, syn, ar, st, diag, cdt, rt, pdt, at]
for m in modules:
    importlib.reload(m)

import importlib
import aws_context as awsc
import knowledge_retrieval as kr
 
session = boto3.Session(
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1",
)
 
awsc.set_session(session)
 

results = []
tests = [
    ("process_data_tool", at.test_process_data_tool),
    ("router_process_data", at.test_router_process_data),
    ("prediction_tool", at.test_prediction_tool),
    ("router_prediction", at.test_router_prediction),
    ("shap_tool", at.test_shap_tool),
    ("router_shap", at.test_router_shap),
    ("router_cost_driver", at.test_router_cost_driver),
    ("cost_driver_wrapper", at.test_cost_driver_wrapper),
    ("knowledge_tool", at.test_knowledge_tool),
    ("answer_orchestrated", at.test_answer_orchestrated),
    ("parse_diagnosis", at.test_parse_diagnosis),
    ("parse_recommendation_query", at.test_parse_recommendation_query),
    ("parse_scenario", at.test_parse_scenario),
    ("plan_diagnosis_only", at.test_plan_diagnosis_only),
    ("plan_recommendation", at.test_plan_recommendation),
    ("plan_scenario_only", at.test_plan_scenario_only),
    ("scenario_tool", at.test_scenario_tool),
    ("diagnosis_tool", at.test_diagnosis_tool),
    ("cost_driver_tool", at.test_cost_driver_tool),
    ("recommendation_tool", at.test_recommendation_tool),
    ("execute_recommendation_plan", at.test_execute_recommendation_plan),
    ("synthesize_recommendation_plan", at.test_synthesize_recommendation_plan),
    ("router_diagnosis", at.test_router_diagnosis),
    ("router_recommendation", at.test_router_recommendation),
    ("router_scenario", at.test_router_scenario),
]
for name, fn in tests:
    results.append(at.run_test(name, fn))

results_df = pd.DataFrame(results)
results_df

# Report

In [5]:
import pandas as pd
from utility import _process_data, _turnup_data, setpoint_df, _summary_cost_plot, make_model_cost
from datetime import date, timedelta
import plotly.io as pio
from pathlib import Path
import pickle


steam_null = False
turnup_data = _turnup_data(True, "", None, setpoint_df, steam_null)

max_date = turnup_data["Wedge_Time"].max()
min_date = turnup_data["Wedge_Time"].min()

last_friday = max_date - pd.to_timedelta((max_date.weekday() - 4) % 7, unit="D")
target_start = last_friday - pd.Timedelta(days=4)      # Monday
target_end_exclusive = last_friday + pd.Timedelta(days=1)  # Saturday (exclusive end)
target_range = (target_start.date(), target_end_exclusive.date())
end_date=min(target_start.date() - timedelta(days=1),max_date.date())
baseline_start = end_date - pd.Timedelta(weeks=4)
baseline_end = end_date
baseline_range = (baseline_start, baseline_end)

period_md = f"{baseline_start.strftime('%B %d, %Y')} – {target_end_exclusive.strftime('%B %d, %Y')}"

process_data =  _process_data(turnup_data, target_range, baseline_range, steam_null)

plotly_theme = "plotly_white"

grades_summary = ["3200115", "6010085", "6010100", "6010120"]

def fibre_cost(row):
    basis_weight = row["Current_basis_weight"]
    starch_uptake = row["Starch_uptake__g/m2_"]
    moisture = row["Current_reel_moisture_average(reel)"]
    return 146.46*(basis_weight*(1-moisture/100)-starch_uptake)/basis_weight

def fibre_features():
    return ["Current_basis_weight","Starch_uptake__g/m2_","Current_reel_moisture_average(reel)"]

MODELS_DIR = Path("models").resolve()

with open(MODELS_DIR / "model_electricity.pkl", "rb") as f:
    electricity_model = pickle.load(f)

with open(MODELS_DIR / "model_steam.pkl", "rb") as f:
    steam_model = pickle.load(f)

with open(MODELS_DIR / "model_starch.pkl", "rb") as f:
    starch_model = pickle.load(f)

def steam_features():
    return list(steam_model.best_estimator_.feature_names_in_)

def electricity_features():
    return list(electricity_model.best_estimator_.feature_names_in_)

def starch_features():
    return list(starch_model.best_estimator_.feature_names_in_)

steam_cost = make_model_cost(steam_model, steam_features)
electricity_cost = make_model_cost(electricity_model, electricity_features)
starch_cost = make_model_cost(starch_model, starch_features)

descriptions = []

LANG = "en"

c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator Ridge from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
c:\workspace\costimiser\.venv\Lib\site-packages\sklearn\base.py:442: InconsistentVersionWarning: Trying to unpickle estimator GridSearchCV from version 1.7.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [7]:
from utility import _summary_cost_plot

x_variable_summary = "week"
y_variable_summary = "Combined_cost__€/T_"
y_variable_summary_secondary = "Overprocessing_percentage"
color_variable_summary = "grade"

fig = _summary_cost_plot(process_data = process_data, 
                        x_variable_summary = x_variable_summary, 
                        y_variable_summary = y_variable_summary, 
                        y_variable_summary_secondary = y_variable_summary_secondary, 
                        color_variable_summary = color_variable_summary, 
                        type_summary = "bar", 
                        trim_summary = False, 
                        grades_summary = grades_summary, 
                        summary_bar_lines=True,
                        plotly_theme = plotly_theme)

_ = fig.update_layout(legend=dict(orientation="h",xanchor="right",x=0.5),                      
                      title=dict(text=f"Summary of {y_variable_summary} by {x_variable_summary}")
                      ),
fig.show()

In [11]:
descriptions = []

In [4]:
from utility import drilldown_df, _drilldown_analysis_plot, mix_effect, build_drilldown_text

for level in [1, 2, 3]:
    for object_drilldown in ["cost", "overprocessing"]:
        
        reference = "baseline"

        drilldown = drilldown_df(process_data[process_data.AB_Grade_ID.isin(grades_summary)], level , object_drilldown, reference)
        if level == 1 and object_drilldown=="cost":
            mix_contribution = mix_effect(object_drilldown, reference, grades_summary, process_data)
        else:
            mix_contribution = None

        descriptions_md = build_drilldown_text(drilldown.rename(columns={"cost":object_drilldown}), mix_contribution, lang=LANG)
        descriptions.append(descriptions_md)

        fig = _drilldown_analysis_plot(drilldown, mix_contribution,  level, object_drilldown, reference)
        fig = fig.update_layout(
                    title="",
                )
        fig.show()

In [31]:
target_range

(datetime.date(2026, 3, 9), datetime.date(2026, 3, 14))

In [32]:
baseline_range

(datetime.date(2026, 2, 8), datetime.date(2026, 3, 8))

In [33]:
turnup_data = _turnup_data(True, "", None, setpoint_df, steam_null)
process_data =  _process_data(turnup_data, target_range, baseline_range, steam_null)

In [6]:
target_range

(datetime.date(2026, 3, 9), datetime.date(2026, 3, 14))

In [42]:
process_data_clustered

Empty DataFrame
Columns: [Current_basis_weight, Starch_uptake__g/m2_, Current_reel_moisture_average(reel), Fibre_cost__€/T_, AB_Grade_ID, target, cluster]
Index: []

In [40]:
import utility
importlib.reload(utility)

In [43]:
process_data_clustered = _process_data_clustered("", process_data, 'Steam__€/T_', "6010120", steam_features())

In [138]:
from utility import _process_data_clustered, _process_data_clustered_summary, _shapley_contrib, _working_plot, _cost_driver_plot, build_shapley_text

for grade_drilldown in ["6010085", "3200115", "6010100", "6010120"][0:1]:
    for cost_component_drilldown in ['Fibre_cost__€/T_', 'Steam__€/T_', 'Electricity__€/T_', 'Starch__€/T_'][0:1]:
        
        if cost_component_drilldown == 'Fibre_cost__€/T_':
            cost_component_features = fibre_features()
        elif cost_component_drilldown == 'Steam__€/T_':
            cost_component_features = steam_features()
        elif cost_component_drilldown == 'Electricity__€/T_':
            cost_component_features = electricity_features()
        elif cost_component_drilldown == 'Starch__€/T_':
            cost_component_features = starch_features()

        process_data_clustered = _process_data_clustered("", process_data, cost_component_drilldown, grade_drilldown, cost_component_features)
        if len(process_data_clustered)>0 and "current" in process_data_clustered.target.unique() and "historic" in process_data_clustered.target.unique():
            df1, df2 = _process_data_clustered_summary(process_data_clustered, cost_component_drilldown, grade_drilldown, fibre_cost, steam_cost, electricity_cost, starch_cost, steam_features, electricity_features, starch_features, fibre_features)

            shapley_contrib = _shapley_contrib("", df1, df2, cost_component_drilldown, grade_drilldown, fibre_cost, steam_cost, electricity_cost, starch_cost, steam_features, electricity_features, starch_features, fibre_features)

            shapley_md = build_shapley_text(shapley_contrib, top_frac=0.20, lang=LANG)
            descriptions.append(shapley_md)

            fig = _cost_driver_plot(shapley_contrib)
            fig.show()

['historic' 'current']

In [139]:
df1

,Current_basis_weight,Starch_uptake__g/m2_,Current_reel_moisture_average(reel),AB_Grade_ID,Fibre_cost__€/T_,unknown
0,85.305527,4.337425,8.012970,6010085,127.277344,0.000000
1,85.618385,4.158588,8.021144,6010085,127.598503,0.000008
2,85.068733,4.190773,8.004661,6010085,127.521263,0.000000
3,84.274841,4.171625,8.040000,6010085,127.434822,-0.000008
4,84.582726,4.195351,8.040000,6010085,127.420120,0.000000
5,84.629379,4.233826,8.069349,6010085,127.314560,0.000008
6,85.230721,4.248186,8.040000,6010085,127.384575,0.000000
7,85.134468,4.238688,8.016228,6010085,127.427460,0.000000
8,84.735077,4.244858,8.010558,6010085,127.390724,0.000000
9,85.524132,4.231835,8.001578,6010085,127.493889,0.000008
10,84.617157,4.201730,8.034343,6010085,127.420326,-0.000008
11,84.077347,3.728557,7.908235,6010085,128.382584,0.000000
12,84.138313,3.751767,8.051786,6010085,128.136627,0.000000
13,83.635612,3.787160,7.895312,6010085,128.264572,0.000000
14,84.393082,3.768917,8.024861,6010085,128.166031,-0.000015
15,84.032829,4.078726,8.042576,6010085,127.572083,0.000000
16,84.471771,3.768833,8.200000,6010085,127.915741,-0.000015
17,84.497665,3.777429,7.953529,6010085,128.263840,0.000000
18,83.614166,3.823295,8.010000,6010085,128.031601,-0.000015
19,84.244324,3.887075,8.069409,6010085,127.883804,-0.000008
20,84.643684,3.838255,7.994157,6010085,128.110382,0.000000
21,84.481895,4.117436,8.028424,6010085,127.563477,-0.000008
22,84.167381,3.940383,8.023127,6010085,127.852661,0.000000
23,84.080864,3.985898,8.075717,6010085,127.689308,0.000008
24,84.441055,4.116308,8.055291,6010085,127.522629,0.000000
25,83.671082,3.975869,8.008170,6010085,127.771774,0.000000
26,84.497948,3.983992,8.070000,6010085,127.735252,0.000015
27,83.910866,3.981673,7.988611,6010085,127.810188,0.000008
28,84.042404,4.079949,8.117485,6010085,127.461044,0.000000
29,84.242989,4.007176,8.070720,6010085,127.672974,0.000000
30,83.995888,4.295288,8.120089,6010085,127.077812,0.000000
31,84.116203,4.070035,8.139999,6010085,127.451591,0.000023
32,84.544525,3.902230,7.946297,6010085,128.061874,0.000000
33,83.687920,4.235537,8.013857,6010085,127.310402,-0.000015
34,84.251076,3.861042,8.020000,6010085,128.001968,-0.000015
35,83.924263,3.771191,8.028860,6010085,128.119659,0.000000
36,84.025688,4.007056,8.128000,6010085,127.571289,0.000000
37,84.355911,3.949920,7.995942,6010085,127.891243,0.000008
38,83.754768,3.835029,7.990000,6010085,128.051620,0.000000
39,84.187378,3.867034,8.041288,6010085,127.955299,0.000008
40,83.998810,3.840044,8.029725,6010085,128.004181,0.000000
41,84.208931,3.865888,8.040000,6010085,127.960884,0.000000
42,84.014297,3.878183,8.062065,6010085,127.891579,0.000008
43,84.136284,3.908174,8.040000,6010085,127.881470,-0.000015
44,83.819244,3.981382,8.079615,6010085,127.669807,0.000000
45,83.812157,3.894276,8.059999,6010085,127.850159,0.000015
46,83.986176,3.881989,8.028411,6010085,127.931953,0.000008
47,84.314209,3.925945,8.046217,6010085,127.855873,0.000008
48,84.102570,3.981394,8.038166,6010085,127.753944,0.000008
49,84.358391,3.980902,8.054301,6010085,127.752190,0.000015
50,83.849739,3.862415,8.002591,6010085,127.992935,-0.000015
51,83.932304,3.883386,8.039380,6010085,127.909111,-0.000008
52,84.440483,3.848190,8.034166,6010085,128.018570,0.000000
53,84.295792,3.886936,7.998537,6010085,127.991966,-0.000015
54,84.084099,3.835664,7.975125,6010085,128.098572,-0.000015
55,83.930450,3.758708,8.161538,6010085,127.947601,-0.000015

In [50]:
shapley_contrib

  AB_Grade_ID                             variable  contribution  value_change
0     6010085                 Current_basis_weight     -0.033087     -0.082352
1     6010085                 Starch_uptake__g/m2_     -1.106420      0.132245
2     6010085  Current_reel_moisture_average(reel)      0.139507     -0.019793

# AI Process Analysis API

In [5]:
from datetime import datetime

target_from = "2026-03-09"
target_to = "2026-03-14"
baseline_from = "2026-02-08"
baseline_to = "2026-03-26"

if isinstance(target_from, str):
    target_from = datetime.strptime(target_from, "%Y-%m-%d").date()

if isinstance(target_to, str):
    target_to = datetime.strptime(target_to, "%Y-%m-%d").date()

if isinstance(baseline_from, str):
    baseline_from = datetime.strptime(baseline_from, "%Y-%m-%d").date()

if isinstance(baseline_to, str):
    baseline_to = datetime.strptime(baseline_to, "%Y-%m-%d").date()

process_data =  _process_data(turnup_data, (target_from,target_to), (baseline_from,baseline_to), steam_null=False)

NameError: name '_process_data' is not defined

In [25]:
import requests
 
url = "http://localhost:8000/shapley_contribution"
 
payload = {
    "target_from": "2026-03-09",
    "target_to": "2026-03-14",
    "baseline_from": "2026-02-08",
    "baseline_to": "2026-03-8",
    "grade": "6010120",
    "cost_component": "steam"
}
 
response = requests.post(url, json=payload)
 
# Check response
response.raise_for_status()
 
data = response.json()
 
print(data)

{'target_from': '2026-03-09', 'target_to': '2026-03-14', 'baseline_from': '2026-02-08', 'baseline_to': '2026-03-08', 'grade': '6010120', 'cost_component': 'steam', 'rows': [{'AB_Grade_ID': '6010120', 'variable': 'Moisture_out_of_PreDryer', 'contribution': -0.006036230859906495, 'value_change': -0.021042823791503906}, {'AB_Grade_ID': '6010120', 'variable': 'concentration_starch_working_tank_2', 'contribution': 0.026972852112671673, 'value_change': -0.005706071853637695}, {'AB_Grade_ID': '6010120', 'variable': 'Steam_temperature_for_PM', 'contribution': -0.8590090566558787, 'value_change': 4.2925262451171875}, {'AB_Grade_ID': '6010120', 'variable': 'Starch_uptake_by_paper_Top_Roll__g/m2_', 'contribution': 0.1698218529371522, 'value_change': 0.11623919010162354}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wire_suction_box_2', 'contribution': 0.15976461584895907, 'value_change': -0.008453786373138428}, {'AB_Grade_ID': '6010120', 'variable': 'Current_basis_weight', 'contribution': -0.01082205326915921, 'value_change': 0.0797882080078125}, {'AB_Grade_ID': '6010120', 'variable': 'PD2_Fabric_tension', 'contribution': 0.10218574968113381, 'value_change': 0.03321027755737305}, {'AB_Grade_ID': '6010120', 'variable': 'Cylinder_38_differential_pressure', 'contribution': 0.3654547178929043, 'value_change': -0.0062977224588394165}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_wet_suction_box', 'contribution': 0.4785378499380207, 'value_change': 0.00047582387924194336}, {'AB_Grade_ID': '6010120', 'variable': 'Current_reel_width', 'contribution': 0.02742795165876673, 'value_change': -1.28790283203125}, {'AB_Grade_ID': '6010120', 'variable': 'Vacuum_uhle-box_bottom_felt', 'contribution': -0.9833853621252934, 'value_change': -0.04466471076011658}, {'AB_Grade_ID': '6010120', 'variable': 'Top_wire_tenstion', 'contribution': 0.0406972185354464, 'value_change': -0.0032110214233398438}, {'AB_Grade_ID': '6010120', 'variable': 'Fixative_2_mass_flow__g/T_', 'contribution': 1.4864314607911941, 'value_change': -369.2775573730469}, {'AB_Grade_ID': '6010120', 'variable': 'concentration_starch_working_tank_1', 'contribution': -0.0316699541182288, 'value_change': 0.0038777589797973633}, {'AB_Grade_ID': '6010120', 'variable': 'Starch_uptake_by_paper_Bottom_Roll__g/m2_', 'contribution': 0.7613909362873627, 'value_change': 0.525388240814209}, {'AB_Grade_ID': '6010120', 'variable': 'Linepressure_1st_press_DS__bar_', 'contribution': 0.49915013124113095, 'value_change': -0.0476837158203125}, {'AB_Grade_ID': '6010120', 'variable': 'Storage_tank_temperature', 'contribution': -0.15723334110274614, 'value_change': 0.5904769897460938}, {'AB_Grade_ID': '6010120', 'variable': 'retention', 'contribution': 0.2267712238917726, 'value_change': -0.0400770902633667}, {'AB_Grade_ID': '6010120', 'variable': 'Dissolved_gas_before_dilution_water_deculator', 'contribution': -0.952637974187497, 'value_change': 0.5144325494766235}, {'AB_Grade_ID': '6010120', 'variable': 'Linepressure_shoe_press__bar_', 'contribution': 0.16527662280559152, 'value_change': -0.0123291015625}, {'AB_Grade_ID': '6010120', 'variable': 'Total_Dewatering_Press', 'contribution': -0.13798264113114111, 'value_change': 116.653564453125}, {'AB_Grade_ID': '6010120', 'variable': 'Speed_PD1', 'contribution': -0.7804777712819339, 'value_change': 59.787841796875}, {'AB_Grade_ID': '6010120', 'variable': 'Jet/wire_ratio', 'contribution': -0.11303901369973614, 'value_change': -1.8956069946289062}, {'AB_Grade_ID': '6010120', 'variable': 'DG4_Temperature_Inlet_Air', 'contribution': 0.5224102148094141, 'value_change': 4.555274963378906}]}