In [1]:
import pandas as pd
import seaborn as sns

sns.set(rc={"figure.figsize":(12, 4)})
sns.set_style('whitegrid')
sns.set_context('notebook')

In [2]:
with open("wedge_vars.txt", "rb") as f:
    raw = f.read(2000)
 
print(raw[:1000])

b'Time\tNiveau Farbe 1 Gelb [0..100 %]\tZulaufmenge Reaktor 4 [0..240 m\xc2\xb3/h] \tgemessenes Fl\xc3\xa4chengewicht in g/m\xc2\xb2\tFrischwasser f\xc3\xbcr Kl\xc3\xa4ranlage m\xc2\xb3/h\tDurchflu\xc3\x9f messung Schleuse Sektion 2 \tSchlamm zur PM [0..100 m\xc2\xb3/h] \tZulaufmenge Reaktor 1 [0..300 m\xc2\xb3/h] \tZulaufmenge Reaktor 2 [0..300 m\xc2\xb3/h] \tZulaufmenge Reaktor 3 [0..300 m\xc2\xb3/h] \tKurzfaser von B06 : Messwert [0..20000 l/min] \tLangfaser von B07 : Messwert [0..10000 l/min] \tTrockenausschuss : Messwert [0..10000 l/min] \tNassausschuss : Messwert [0..32000 l/min] \tEnergie Z\xc3\xa4hler PM-Antrieb in KWh\tEnergie Z\xc3\xa4hler PM-Antrieb in MWh\tEnergie Z\xc3\xa4hler PM-Antrieb in KWh~^0\tEnergie Z\xc3\xa4hler PM-Antrieb in KWh~^1\tDampf Z\xc3\xa4hler PM1 in t~^2\tDampf Z\xc3\xa4hler PM1 in t~^3\tBetrieb Silikonauftrag Zyl. 1 [0..1 ] \tCurrent year Virtual Tag for generating Jumbo ID \tDampf Z\xc3\xa4hler PM1 in t\tDampf Z\xc3\xa4hler PM1 in t~^0\tBetrieb Expresscleaner 1 [0..1 ] \tBetrieb Expresscleaner 2 [0..1 ] \tBetrieb Expresscleaner 3 [0..1 ] \tBetrieb Expresscleaner 4 [0..1 ] \tStoffdichte Mischb\xc3'

In [3]:
path = "wedge_vars.txt"
 
with open(path, "rb") as f:
    raw = f.read(4000)
 
print("First 120 bytes:", raw[:120])
print("\n-----\nAs UTF-8 (replace errors):\n-----")
print(raw.decode("utf-8", errors="replace")[:800])
print("\n-----\nAs CP1252 (replace errors):\n-----")
print(raw.decode("cp1252", errors="replace")[:800])

First 120 bytes: b'Time\tNiveau Farbe 1 Gelb [0..100 %]\tZulaufmenge Reaktor 4 [0..240 m\xc2\xb3/h] \tgemessenes Fl\xc3\xa4chengewicht in g/m\xc2\xb2\tFrischwass'

-----
As UTF-8 (replace errors):
-----
Time	Niveau Farbe 1 Gelb [0..100 %]	Zulaufmenge Reaktor 4 [0..240 m³/h] 	gemessenes Flächengewicht in g/m²	Frischwasser für Kläranlage m³/h	Durchfluß messung Schleuse Sektion 2 	Schlamm zur PM [0..100 m³/h] 	Zulaufmenge Reaktor 1 [0..300 m³/h] 	Zulaufmenge Reaktor 2 [0..300 m³/h] 	Zulaufmenge Reaktor 3 [0..300 m³/h] 	Kurzfaser von B06 : Messwert [0..20000 l/min] 	Langfaser von B07 : Messwert [0..10000 l/min] 	Trockenausschuss : Messwert [0..10000 l/min] 	Nassausschuss : Messwert [0..32000 l/min] 	Energie Zähler PM-Antrieb in KWh	Energie Zähler PM-Antrieb in MWh	Energie Zähler PM-Antrieb in KWh~^0	Energie Zähler PM-Antrieb in KWh~^1	Dampf Zähler PM1 in t~^2	Dampf Zähler PM1 in t~^3	Betrieb Silikonauftrag Zyl. 1 [0..1 ] 	Current year Virtual Tag for generating Jumbo ID 	Dampf Zähler PM1 in t

-----
As CP1252 (replace errors):
-----
Time	Niveau Farbe 1 Gelb [0..100 %]	Zulaufmenge Reaktor 4 [0..240 mÂ³/h] 	gemessenes FlÃ¤chengewicht in g/mÂ²	Frischwasser fÃ¼r KlÃ¤ranlage mÂ³/h	DurchfluÃŸ messung Schleuse Sektion 2 	Schlamm zur PM [0..100 mÂ³/h] 	Zulaufmenge Reaktor 1 [0..300 mÂ³/h] 	Zulaufmenge Reaktor 2 [0..300 mÂ³/h] 	Zulaufmenge Reaktor 3 [0..300 mÂ³/h] 	Kurzfaser von B06 : Messwert [0..20000 l/min] 	Langfaser von B07 : Messwert [0..10000 l/min] 	Trockenausschuss : Messwert [0..10000 l/min] 	Nassausschuss : Messwert [0..32000 l/min] 	Energie ZÃ¤hler PM-Antrieb in KWh	Energie ZÃ¤hler PM-Antrieb in MWh	Energie ZÃ¤hler PM-Antrieb in KWh~^0	Energie ZÃ¤hler PM-Antrieb in KWh~^1	Dampf ZÃ¤hler PM1 in t~^2	Dampf ZÃ¤hler PM1 in t~^3	Betrieb Silikonauftrag Zyl. 1 [0..1 ] 	Current year Virtual Tag for generating Jumbo ID 	Damp

In [4]:
with open(path, "r", encoding="utf-8", errors="strict") as f:
    for i in range(1, 6):
        line = f.readline()
        print(f"LINE {i}: {repr(line[:250])}")

LINE 1: 'Time\tNiveau Farbe 1 Gelb [0..100 %]\tZulaufmenge Reaktor 4 [0..240 m³/h] \tgemessenes Flächengewicht in g/m²\tFrischwasser für Kläranlage m³/h\tDurchfluß messung Schleuse Sektion 2 \tSchlamm zur PM [0..100 m³/h] \tZulaufmenge Reaktor 1 [0..300 m³/h] \tZulau'
LINE 2: '\tDruck 2.Presse [0..150 kN/m] \tPapierbahnriss Kissendruck [-1 = Abriss] [-2..1 ]\tPapierbahnriss SpeedSizer [-1 = Abriss] [-2..1 ]\tPapierbahnriss TG6 [-1 = Abriss] [-2..1 ]\tVakuum Siebsaugwalze Zone 1 : Messwert [-1..0 bar]\tGeschwindigkeit Siebpartie '
LINE 3: '\tNiveau B55 [-10..110 %] \tStrom Vakuumpumpe 2 Deculator [-10..40 A]\tStrom Stoffauflaufpumpe [0..1260 A]\tStrom Pumpe Sekundärsortierer [-10..60 A]\tStrom Verdünnungswasserpumpe Deculator [0..120 A]\tStrom Pumpe Randstreifenpulper zum B39/40 [-10..60 A]\t'
LINE 4: '\tInstrumentenluft GuD [0..2750 m³/h]\tKompressor 6 Luftmenge\tÜberführ-Luftdruck\tKW-Arbeits-Luftmenge\tAPA-Instrumenten-Luftmenge\tAPA-Arbeits-Luftmenge\tPM-Instrumenten-Luftmenge\tTemperatur Inaktivierung [0..200 °C]~^0\tTemperatur Vorratsbehälter [0..150 '
LINE 5: '  \t%\tm³/h\t\tM3/HR\tm³/h\tm³/h\tm³/h\tm³/h\tm³/h\tL/MIN\tL/MIN\tL/MIN\tL/MIN\tKWH\tMWH\tKWH\tKWH\tTONNE\tTONNE\t\t\tTONNE\tTONNE\t\t\t\t\t\t%\t%\t%\t\t\tKN/M\tKN/M\tKN/M\tg/m²\t%\t%\t%\tKN/M\t%\t%\t%\t%\t%\t%\t%\t%\tG/KG\tG/KG\t%\t%\tBAR\tG/KG\tG/KG\tG/KG\tt/h\tt/h\tt/h\tt/h\tVol%\tV/V %\tTONNE/HR\tTONNE/HR\t\t\t°C'

In [7]:
with open(path, "r", encoding="utf-8", errors="replace") as f:
    for i in range(7):
        line = next(f)
        print(f"\nLINE {i+1}")
        print("chars:", len(line))
        print("tabs:", line.count("\t"))
        print(repr(line[:300]))

LINE 1
chars: 4163
tabs: 117
'Time\tNiveau Farbe 1 Gelb [0..100 %]\tZulaufmenge Reaktor 4 [0..240 m³/h] \tgemessenes Flächengewicht in g/m²\tFrischwasser für Kläranlage m³/h\tDurchfluß messung Schleuse Sektion 2 \tSchlamm zur PM [0..100 m³/h] \tZulaufmenge Reaktor 1 [0..300 m³/h] \tZulaufmenge Reaktor 2 [0..300 m³/h] \tZulaufmenge Reakto'

LINE 2
chars: 21782
tabs: 496
'\tDruck 2.Presse [0..150 kN/m] \tPapierbahnriss Kissendruck [-1 = Abriss] [-2..1 ]\tPapierbahnriss SpeedSizer [-1 = Abriss] [-2..1 ]\tPapierbahnriss TG6 [-1 = Abriss] [-2..1 ]\tVakuum Siebsaugwalze Zone 1 : Messwert [-1..0 bar]\tGeschwindigkeit Siebpartie [0..1500 m/min]\tPapier in Presse (PickUp) [-2..1 ]'

LINE 3
chars: 21052
tabs: 458
'\tNiveau B55 [-10..110 %] \tStrom Vakuumpumpe 2 Deculator [-10..40 A]\tStrom Stoffauflaufpumpe [0..1260 A]\tStrom Pumpe Sekundärsortierer [-10..60 A]\tStrom Verdünnungswasserpumpe Deculator [0..120 A]\tStrom Pumpe Randstreifenpulper zum B39/40 [-10..60 A]\tStrom Pumpe Trockenausschuss [-10..60 A]\tStrom Pum'

LINE 4
chars: 60443
tabs: 1203
'\tInstrumentenluft GuD [0..2750 m³/h]\tKompressor 6 Luftmenge\tÜberführ-Luftdruck\tKW-Arbeits-Luftmenge\tAPA-Instrumenten-Luftmenge\tAPA-Arbeits-Luftmenge\tPM-Instrumenten-Luftmenge\tTemperatur Inaktivierung [0..200 °C]~^0\tTemperatur Vorratsbehälter [0..150 °C]\tLuftmenge gesamt [0..6000 m³/h]\tKW-Instrumente'

LINE 5
chars: 6764
tabs: 2274
'  \t%\tm³/h\t\tM3/HR\tm³/h\tm³/h\tm³/h\tm³/h\tm³/h\tL/MIN\tL/MIN\tL/MIN\tL/MIN\tKWH\tMWH\tKWH\tKWH\tTONNE\tTONNE\t\t\tTONNE\tTONNE\t\t\t\t\t\t%\t%\t%\t\t\tKN/M\tKN/M\tKN/M\tg/m²\t%\t%\t%\tKN/M\t%\t%\t%\t%\t%\t%\t%\t%\tG/KG\tG/KG\t%\t%\tBAR\tG/KG\tG/KG\tG/KG\tt/h\tt/h\tt/h\tt/h\tVol%\tV/V %\tTONNE/HR\tTONNE/HR\t\t\t°C\t%\tm³/h\tm³/h\tm³\tMWH\tKg\tCM\t\t\tM\tM\tM/MIN\tKg\t\t\t\tM\tM/MI'

LINE 6
chars: 39427
tabs: 2274
'  \t2-008-LI080_05_1-X\tFIC60_7_X\tFLG_GEPRUEFT\tFRISCHWASSER_KLAERANLAGE\tFT009-X\tFC65_5_X\tFIC60_3_X\tFIC60_4_X\tFIC60_5_X\tFC031.01-KF_DURCHFLUSS\tFC031.02-LF_DURCHFLUSS\tFC031.03-TROCKENAUSSCHUSS\tFC031.04-NASSAUSSCHUSS\tEN_Z_PM1_ABRISS\tEN_Z_PM1_GES\tEN_Z_PM1_PROD\tEN_Z_PM1_STILLSTAND\tDAMPF_Z_PM1_PROD\tDAMPF_Z_'

LINE 7
chars: 31072
tabs: 2274
'2026-03-14 16:51:00\t72.65645980834961\t79.9754492549573\t50\t1.399999976158142\tNaN\t33.60698318481445\t114.6726100081104\t114.6227732512911\t114.8900657265873\t12678\t7468.492450420673\t1509.523080679086\t1099.615384615385\tNaN\tNaN\tNaN\tNaN\tNaN\tNaN\tNaN\t86444\tNaN\tNaN\tNaN\tNaN\tNaN\tNaN\tNaN\t3.400000095367432\t4.204999'

In [8]:
with open(path, "r", encoding="utf-8", errors="replace") as f:
    lines = [next(f).rstrip("\n\r") for _ in range(7)]
 
for i, line in enumerate(lines, start=1):
    fields = line.count("\t") + 1
    print(f"Line {i}: {fields} fields")

Line 1: 118 fields
Line 2: 497 fields
Line 3: 459 fields
Line 4: 1204 fields
Line 5: 2275 fields
Line 6: 2275 fields
Line 7: 2275 fields

In [9]:
with open(path, "r", encoding="utf-8", errors="replace") as f:
    line1 = next(f).rstrip("\n\r").split("\t")
    line2 = next(f).rstrip("\n\r").split("\t")
    line3 = next(f).rstrip("\n\r").split("\t")
    line4 = next(f).rstrip("\n\r").split("\t")
    units = next(f).rstrip("\n\r").split("\t")
    tags  = next(f).rstrip("\n\r").split("\t")

In [10]:
names = line1 + line2[1:] + line3[1:] + line4[1:]

In [11]:
print("names:", len(names))
print("units:", len(units))
print("tags :", len(tags))

names: 2275
units: 2275
tags : 2275

In [12]:
import pandas as pd
 
names = pd.Series(names, dtype="string")
names = names.str.replace(r"\s+", " ", regex=True).str.strip()
 
if names.iloc[0] == "" or pd.isna(names.iloc[0]):
    names.iloc[0] = "Time"

In [14]:
def make_unique(cols):
    seen = {}
    out = []
    for c in cols:
        c = str(c).strip()
        if c == "":
            c = "Unnamed"
        if c not in seen:
            seen[c] = 0
            out.append(c)
        else:
            seen[c] += 1
            out.append(f"{c}__{seen[c]}")
    return out
 
names = make_unique(names.tolist())

In [5]:
# Read first 5 lines (4 name rows + 1 units row) as raw strings
hdr = pd.read_csv(path, sep="\t", header=None, nrows=5, encoding="utf-8", engine="python")
print("Header shape:", hdr.shape)
 
# Combine name rows 1-4 into one column name per field
names = hdr.iloc[0].fillna("").astype(str)
for r in [1, 2, 3]:
    names = names + hdr.iloc[r].fillna("").astype(str)
 
# Clean up
names = (names
         .str.replace(r"\s+", " ", regex=True)
         .str.strip())
 
# Make the first column name sane (it should be Time)
if names.iloc[0] == "":
    names.iloc[0] = "Time"
 
print("\nFirst 10 combined column names:")
print(names.head(10).to_list())
 
# Now read a small sample of the actual data (skip the 5 header lines)
df_sample = pd.read_csv(
    path,
    sep="\t",
    header=None,
    names=names,
    skiprows=5,
    nrows=5,
    encoding="utf-8",
    engine="python"
)
 
print("\nSample data:")
print(df_sample.head())
print("\nDtypes:")
print(df_sample.dtypes.head(10))

ParserError: Expected 118 fields in line 2, saw 497

In [44]:
with open(path, "r", encoding="utf-8", errors="strict") as f:
    for i in range(1, 8):
        line = f.readline()
        n_fields = line.count("\t") + 1
        print(f"LINE {i}: fields={n_fields}, chars={len(line)}")

LINE 1: fields=113, chars=5252
LINE 2: fields=39, chars=1589
LINE 3: fields=1036, chars=49136
LINE 4: fields=1090, chars=51463
LINE 5: fields=2275, chars=6764
LINE 6: fields=2275, chars=39427
LINE 7: fields=2275, chars=30579

In [45]:
import re
 
def is_time_start(s: str) -> bool:
    s = s.strip()
    # Accept common timestamp patterns: "2026-02-12 08:00:00" or "12.02.2026 08:00:00"
    return bool(re.match(r"^(\d{4}-\d{2}-\d{2}|\d{2}\.\d{2}\.\d{4})\s+\d{2}:\d{2}:\d{2}", s))
 
with open(path, "r", encoding="utf-8", errors="strict") as f:
    for idx, line in enumerate(f, start=1):
        first_cell = line.split("\t", 1)[0]
        if is_time_start(first_cell):
            print("First data row line number:", idx)
            print("First cell:", first_cell)
            print("Fields in this line:", line.count("\t") + 1)
            print("Preview:", repr(line[:200]))
            break

First data row line number: 7
First cell: 2026-02-11 12:31:00
Fields in this line: 2275
Preview: '2026-02-11 12:31:00\t1143.977783203125\t1176.662521362305\t29.0759391784668\t4.692428038670467\t61.0427630497859\t89.01837686391977\t24.45834042475774\t2.836843508940476\t52.17922973632812\t88.99634199876051\t8.'

In [47]:
with open(path, "r", encoding="utf-8", errors="strict") as f:
    for i in range(1, 20):
        line = f.readline()
        n_fields = line.count("\t") + 1
        if n_fields == 2275:
            print("Found header-width line:", i)
            print("First 120 chars:", repr(line[:120]))
            print("Starts with:", repr(line.split("\t", 1)[0]))

Found header-width line: 5
First 120 chars: '  \tM/MIN\tM/MIN\t%\tM3/HR\t%\tM3/HR\t%\tM3/HR\t%\tM3/HR\tM3/HR\t\tM3/HR\tBAR\tBAR\tBAR\tBAR\tBAR\tBAR\tBAR\tBAR\tBAR\t%\tC\tBAR\tBAR\tBAR\tBAR\tBAR\t'
Starts with: '  '
Found header-width line: 6
First 120 chars: '  \t2-003-UZ001-MD_SPEED-X\t2-033-UZ001-MD_SPEED-X\t2-033-FC100-Y\t2-033-FC100-X\t2-033-FC150-Y\t2-033-FC150-X\t2-033-FC200-Y\t2'
Starts with: '  '
Found header-width line: 7
First 120 chars: '2026-02-11 12:31:00\t1143.977783203125\t1176.662521362305\t29.0759391784668\t4.692428038670467\t61.0427630497859\t89.018376863'
Starts with: '2026-02-11 12:31:00'

In [49]:
df = pd.read_csv(
    path,
    sep="\t",
    skiprows=5,            # skip lines 1-5 (incl units row)
    header=0,              # line 6 becomes header
    encoding="utf-8",
    engine="python"
)
 
# Rename first column (blank header) to Time
df = df.rename(columns={df.columns[0]: "Time"})
df["Time"] = pd.to_datetime(df["Time"], errors="coerce")
 
print("Shape:", df.shape)
print("Columns (first 10):", df.columns[:10].to_list())
print(df[["Time"]].head())
print("Time nulls:", df["Time"].isna().sum())

Shape: (1, 2275)
Columns (first 10): ['Time', '2-003-UZ001-MD_SPEED-X', '2-033-UZ001-MD_SPEED-X', '2-033-FC100-Y', '2-033-FC100-X', '2-033-FC150-Y', '2-033-FC150-X', '2-033-FC200-Y', '2-033-FC200-X', '2-033-FC250-Y']
                 Time
0 2026-02-11 12:31:00
Time nulls: 0

In [17]:
# --- 1) Read the known-good "units" and "tags" lines using plain text ---
def get_line(path, line_no, encoding="utf-8"):
    with open(path, "r", encoding=encoding, errors="strict") as f:
        for i, line in enumerate(f, start=1):
            if i == line_no:
                return line.rstrip("\n")
    raise ValueError(f"Line {line_no} not found")
 
units_line = get_line(path, 5)   # from our diagnosis
tags_line  = get_line(path, 6)
 
units = units_line.split("\t")
tags  = tags_line.split("\t")
 
# First cell is blank in both -> make it Time
tags[0] = "Time"
units[0] = "datetime"
 
# --- 2) Read the data safely, enforcing the expected number of columns ---
expected_cols = len(tags)  # should be 2275
 
# Use only the first expected_cols fields per row (protect against stray tabs later)
usecols = list(range(expected_cols))
 
df = pd.read_csv(
    path,
    sep="\t",
    skiprows=6,          # skip lines 1-6 (descriptions + units + tags)
    header=None,
    names=tags,
    usecols=usecols,
    encoding="utf-8",
    engine="python",
    on_bad_lines="skip", # if a row is truly broken, skip it instead of failing
)
 
# Parse Time
df["Time"] = pd.to_datetime(df["Time"], errors="coerce")
 
# --- 3) Build a metadata table: tag -> unit ---
meta = pd.DataFrame({"tag": tags, "unit": units})
 
print("Data shape:", df.shape)
print("Meta shape:", meta.shape)
print(meta.head(10))
print(df.head(3))

Data shape: (1, 2275)
Meta shape: (2275, 2)
                        tag      unit
0                      Time  datetime
1        2-008-LI080_05_1-X         %
2                 FIC60_7_X      m³/h
3              FLG_GEPRUEFT
4  FRISCHWASSER_KLAERANLAGE     M3/HR
5                   FT009-X      m³/h
6                  FC65_5_X      m³/h
7                 FIC60_3_X      m³/h
8                 FIC60_4_X      m³/h
9                 FIC60_5_X      m³/h
                 Time  2-008-LI080_05_1-X  FIC60_7_X  FLG_GEPRUEFT  \
0 2026-03-14 16:51:00            72.65646  79.975449            50

   FRISCHWASSER_KLAERANLAGE  FT009-X   FC65_5_X  FIC60_3_X   FIC60_4_X  \
0                       1.4      NaN  33.606983  114.67261  114.622773

    FIC60_5_X  ...  QO_KONTROLLERAKELSTREIFEN  QO_L/Q_VERHAELT.  \
0  114.890066  ...                          0                 0

   QO_FLG_ONLINE  QO_FLG_VAR_CD15  QO_FLG_VAR_MD  QO_GURLEY  \
0            115             2.82            5.6  33.400002

   QO_FEUCHTE_ONLINE  QO_FLG_2S_CD6  QO_FLG_2S_MD  QO_FLG_AL400
0               8.93            1.3          2.02    112.129997

[1 rows x 2275 columns]

In [18]:
def get_line(path, line_no, encoding="utf-8"):
    with open(path, "r", encoding=encoding, errors="strict") as f:
        for i, line in enumerate(f, start=1):
            if i == line_no:
                return line.rstrip("\n")
    raise ValueError(f"Line {line_no} not found")
 
# Known from your diagnosis
desc_lines = [get_line(path, i) for i in [1, 2, 3, 4]]  # wrapped descriptions
units_line = get_line(path, 5)
tags_line  = get_line(path, 6)
 
# Split units/tags (these are full-width already)
units = units_line.split("\t")
tags  = tags_line.split("\t")
 
# Fix first column name/unit (blank -> Time)
tags[0] = "Time"
units[0] = "datetime"
 
expected_cols = len(tags)  # should be 2275
 
# --- Reconstruct descriptions by concatenating pieces from lines 1-4 ---
desc = []
for k, line in enumerate(desc_lines):
    parts = line.split("\t")
    if k == 0:
        # line 1 includes "Time" then first chunk of descriptions
        # keep same length as header chunk
        desc.extend(parts)
    else:
        # lines 2-4 start with a blank first field -> drop it
        if len(parts) > 0 and parts[0].strip() == "":
            parts = parts[1:]
        desc.extend(parts)
 
# Ensure descriptions align to expected column count
# (pad/truncate defensively in case of small off-by-few issues)
if len(desc) < expected_cols:
    desc = desc + [""] * (expected_cols - len(desc))
else:
    desc = desc[:expected_cols]
 
# Make sure first description is "Time" (optional)
if desc[0].strip() == "":
    desc[0] = "Time"
 
meta = pd.DataFrame({"tag": tags, "unit": units, "description": desc})
 
print("meta shape:", meta.shape)
print(meta.head(10))

meta shape: (2275, 3)
                        tag      unit                            description
0                      Time  datetime                                   Time
1        2-008-LI080_05_1-X         %         Niveau Farbe 1 Gelb [0..100 %]
2                 FIC60_7_X      m³/h   Zulaufmenge Reaktor 4 [0..240 m³/h]
3              FLG_GEPRUEFT                gemessenes Flächengewicht in g/m²
4  FRISCHWASSER_KLAERANLAGE     M3/HR       Frischwasser für Kläranlage m³/h
5                   FT009-X      m³/h  Durchfluß messung Schleuse Sektion 2
6                  FC65_5_X      m³/h          Schlamm zur PM [0..100 m³/h]
7                 FIC60_3_X      m³/h   Zulaufmenge Reaktor 1 [0..300 m³/h]
8                 FIC60_4_X      m³/h   Zulaufmenge Reaktor 2 [0..300 m³/h]
9                 FIC60_5_X      m³/h   Zulaufmenge Reaktor 3 [0..300 m³/h]

In [19]:
import re
import unicodedata
import pandas as pd
 
# --- compiled regexes (fast) ---
 
# tag-like substrings such as 2-033-FI100-D2 or 2-033-FC100
TAG_LIKE = re.compile(r"\b\d+-\d+-[A-Z0-9]+(?:-[A-Z0-9]+)?\b")
 
# complete bracket blocks: [ ... ]
FULL_BRACKET = re.compile(r"\[[^\]]*\]")
 
# dangling bracket interval at end (no closing ])
DANGLING_INTERVAL = re.compile(
    r"\[\s*[-+]?\d+(?:[.,]\d+)?\s*\.\.\s*[-+]?\d+(?:[.,]\d+)?[^]]*$"
)
 
# any remaining lone '['
LONE_OPEN_BRACKET = re.compile(r"\[")
 
# suffix ~^n at end
SUFFIX = re.compile(r"\s*~\^(\d+)\s*$")
 
# invisible characters explicitly
ZW_BOM = re.compile(r"[\u200b\u200c\u200d\u2060\ufeff]")
 
# unit mentions (add more as needed)
UNIT_PATTERNS = [
    r"\(\s*%+\s*\)",
    r"\(\s*vol\s*%\s*\)",
    r"\(\s*vol%\s*\)",
 
    r"\b(in)\s+kwh\b",
    r"\b(in)\s+mwh\b",
    r"\b(in)\s+g\s*/\s*m(?:\^?2|²)\b",
 
    r"\bt\s*/\s*hr\b",
    r"\bl\s*/\s*h\b",
    r"\bl\s*/\s*min\b",
    r"\bm\s*/\s*min\b",
    r"\bm(?:\^?2|²)\b",
    r"\bg\s*/\s*m(?:\^?2|²)\b",
    r"\bm(?:\^?3|³)\s*/\s*h\b",
 
    r"\bkwh\b",
    r"\bmwh\b",
 
    r"\b\d+(?:[.,]\d+)?\s*(?:-|–|\.\.)\s*\d+(?:[.,]\d+)?\s*bar\b",
]
UNITS_RE = re.compile("|".join(f"(?:{p})" for p in UNIT_PATTERNS), flags=re.IGNORECASE)
 
# logic notes to remove
LOGIC_RE = re.compile(
    r"(?:\(\s*0\s*=\s*false\s*\))"
    r"|(?:/\s*no\s*tear\s*=\s*-?1\s*\|\s*tear\s*=\s*0)",
    flags=re.IGNORECASE
)
 
def clean_meta_text(x: object) -> object:
    """Apply all cleaning steps to a single cell."""
    if pd.isna(x):
        return x
 
    s = str(x)
 
    # 1) remove zero-width + BOM explicitly
    s = ZW_BOM.sub("", s)
 
    # 2) remove other unicode control chars (category starts with 'C')
    s = "".join(ch for ch in s if unicodedata.category(ch)[0] != "C")
 
    # 3) ~^n -> (n+1)
    m = SUFFIX.search(s)
    if m:
        n = int(m.group(1))
        s = SUFFIX.sub(f" ({n+1})", s)
 
    # 4) remove tag-like substrings
    s = TAG_LIKE.sub("", s)
 
    # 5) remove proper bracket blocks and dangling intervals
    #s = FULL_BRACKET.sub("", s)
    #s = DANGLING_INTERVAL.sub("", s)
    #s = LONE_OPEN_BRACKET.sub("", s)
 
    # 6) remove logic notes
    #s = LOGIC_RE.sub("", s)
 
    # 7) remove unit mentions
    #s = UNITS_RE.sub("", s)
 
    # 8) normalize whitespace and tidy punctuation leftovers
    s = re.sub(r"\s+", " ", s).strip()
    s = re.sub(r"\s*:\s*$", "", s).strip()

       # 8) normalize whitespace
    s = re.sub(r"\s+", " ", s).strip()
 
    # Remove trailing colon
    s = re.sub(r"\s*:\s*$", "", s).strip()
 
    # Remove leading/trailing dots
    s = re.sub(r"^\.+\s*", "", s)   # dots at start
    s = re.sub(r"\s*\.+$", "", s)   # dots at end
 
    # Final trim
    s = s.strip()
 
    return s
 
def clean_meta_dataframe(meta: pd.DataFrame, columns: list[str]) -> pd.DataFrame:
    """Clean selected columns in meta in-place and return meta."""
    for c in columns:
        if c in meta.columns:
            meta[c] = meta[c].apply(clean_meta_text)
    return meta
 
# --- usage: choose the columns you want cleaned (German + English if present) ---
#cols_to_clean = ["machine_part", "description_text", "machine_part_en", "description_text_en"]
cols_to_clean = ["description"]
meta = clean_meta_dataframe(meta, cols_to_clean)
 
meta[cols_to_clean].head(15)

                                      description
0                                            Time
1                  Niveau Farbe 1 Gelb [0..100 %]
2             Zulaufmenge Reaktor 4 [0..240 m³/h]
3               gemessenes Flächengewicht in g/m²
4                Frischwasser für Kläranlage m³/h
5            Durchfluß messung Schleuse Sektion 2
6                    Schlamm zur PM [0..100 m³/h]
7             Zulaufmenge Reaktor 1 [0..300 m³/h]
8             Zulaufmenge Reaktor 2 [0..300 m³/h]
9             Zulaufmenge Reaktor 3 [0..300 m³/h]
10  Kurzfaser von B06 : Messwert [0..20000 l/min]
11  Langfaser von B07 : Messwert [0..10000 l/min]
12   Trockenausschuss : Messwert [0..10000 l/min]
13      Nassausschuss : Messwert [0..32000 l/min]
14               Energie Zähler PM-Antrieb in KWh

In [20]:
meta

,tag,unit,description
0,Time,datetime,Time
1,2-008-LI080_05_1-X,%,Niveau Farbe 1 Gelb [0..100 %]
2,FIC60_7_X,m³/h,Zulaufmenge Reaktor 4 [0..240 m³/h]
3,FLG_GEPRUEFT,,gemessenes Flächengewicht in g/m²
4,FRISCHWASSER_KLAERANLAGE,M3/HR,Frischwasser für Kläranlage m³/h
...,...,...,...
2270,QO_GURLEY,,QO_Gurley Luftdurchlässigkeit Gurley :1
2271,QO_FEUCHTE_ONLINE,,QO_Feuchte Online Feuchte Poperoller Feuchte O...
2272,QO_FLG_2S_CD6,,QO_FLG 2s CD6 D04
2273,QO_FLG_2S_MD,,QO_FLG 2S MD E05 Basis weight 2sigma MD
2274,QO_FLG_AL400,,QO_Flg AL400 Flächengewicht Prüfstrasse Flg AL...

In [ ]:
import boto3
import json
import pandas as pd
from tqdm.auto import tqdm
import os

session = boto3.Session(
    #profile_name="DatafactoryAdministrator-636452271875",
    profile_name="DatafactoryDeveloper-781690932061",
    region_name="eu-west-1"
)
s3 = session.client("s3")

 
bedrock = session.client("bedrock-runtime", region_name="eu-west-1")
MODEL_ID = "arn:aws:bedrock:eu-west-1:781690932061:inference-profile/eu.anthropic.claude-sonnet-4-5-20250929-v1:0"

SYSTEM_PROMPT = """You are a professional industrial translator.
Translate German industrial variable names into precise technical English.
 
Rules:
- Preserve technical meaning.
- Do not expand plant codes or IDs.
- Do not explain.
- Output MUST be JSON Lines (JSONL): one JSON object per line.
- Each line format: {"src": "<original>", "tgt": "<translation>"}
- Output only JSONL lines, no markdown, no extra text.
"""
 
def _parse_jsonl(text: str) -> dict:
    if not text or not text.strip():
        raise ValueError("Empty model text")
 
    # remove code fences if any
    text = re.sub(r"^```(?:jsonl|json)?\s*", "", text.strip(), flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
 
    mapping = {}
    bad = 0
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
            mapping[obj["src"]] = obj["tgt"]
        except Exception:
            bad += 1
 
    if not mapping:
        raise ValueError(f"No JSONL objects parsed. First 200 chars: {text[:200]!r}")
    return mapping
 
def translate_batch_bedrock_jsonl(strings, max_retries=2):
    user_prompt = "Translate these terms into English. Return JSONL only.\n"
    user_prompt += "\n".join(f"- {s}" for s in strings)
 
    body = {
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 3500,      # keep some headroom
        "temperature": 0,
        "system": SYSTEM_PROMPT,
        "messages": [{"role": "user", "content": user_prompt}],
    }
 
    last_err = None
    for attempt in range(max_retries + 1):
        resp = bedrock.invoke_model(modelId=MODEL_ID, body=json.dumps(body))
        payload = json.loads(resp["body"].read())
        text = payload.get("content", [{}])[0].get("text", "")
 
        try:
            out = _parse_jsonl(text)
            # Fill missing with original
            for s in strings:
                out.setdefault(s, s)
            return out
        except Exception as e:
            last_err = e
            body["messages"].append({
                "role": "user",
                "content": "Your output was not valid JSONL. Output ONLY JSONL lines, one per input bullet."
            })
            time.sleep(0.5)
 
    raise RuntimeError(f"Failed JSONL. Last error: {last_err}")
 
def translate_unique_with_bedrock(values, batch_size=50, min_batch_size=5):
    values = pd.Series(values).dropna().astype(str)
    values = values[values.str.strip() != ""]
    unique_vals = values.unique().tolist()
 
    mapping = {}
    i = 0
    pbar = tqdm(total=len(unique_vals), desc="Translating (Bedrock)", unit="str")
 
    while i < len(unique_vals):
        bs = min(batch_size, len(unique_vals) - i)
        batch = unique_vals[i:i+bs]
 
        try:
            out = translate_batch_bedrock_jsonl(batch)
            mapping.update(out)
            i += bs
            pbar.update(bs)
        except RuntimeError:
            # If it fails, reduce batch size and retry this same chunk
            if bs <= min_batch_size:
                # last resort: keep originals to avoid infinite loop
                for s in batch:
                    mapping.setdefault(s, s)
                i += bs
                pbar.update(bs)
            else:
                batch_size = max(min_batch_size, bs // 2)
 
    pbar.close()
    return mapping
 
# Example usage
desc_map = translate_unique_with_bedrock(meta["description"].unique(), batch_size=80)
 
meta["description_en"] = meta["description"].map(desc_map)

Translating (Bedrock):   0%|          | 0/2258 [00:00<?, ?str/s]

In [24]:
meta

,tag,unit,description,description_en
0,Time,datetime,Time,Time
1,2-008-LI080_05_1-X,%,Niveau Farbe 1 Gelb [0..100 %],Level Color 1 Yellow [0..100 %]
2,FIC60_7_X,m³/h,Zulaufmenge Reaktor 4 [0..240 m³/h],Inlet Flow Reactor 4 [0..240 m³/h]
3,FLG_GEPRUEFT,,gemessenes Flächengewicht in g/m²,Measured Basis Weight in g/m²
4,FRISCHWASSER_KLAERANLAGE,M3/HR,Frischwasser für Kläranlage m³/h,Fresh Water for Wastewater Treatment Plant m³/h
...,...,...,...,...
2270,QO_GURLEY,,QO_Gurley Luftdurchlässigkeit Gurley :1,QO_Gurley Air permeability Gurley :1
2271,QO_FEUCHTE_ONLINE,,QO_Feuchte Online Feuchte Poperoller Feuchte O...,QO_Moisture Online Moisture Poperoller Moistur...
2272,QO_FLG_2S_CD6,,QO_FLG 2s CD6 D04,QO_FLG 2s CD6 D04
2273,QO_FLG_2S_MD,,QO_FLG 2S MD E05 Basis weight 2sigma MD,QO_FLG 2S MD E05 Basis weight 2sigma MD
2274,QO_FLG_AL400,,QO_Flg AL400 Flächengewicht Prüfstrasse Flg AL...,QO_Flg AL400 Basis weight Test line Flg AL400 :54

In [25]:
df_tags = pd.read_csv("data/tags-v3.csv", sep=';')

In [34]:
meta = pd.concat([meta, df_tags.rename(columns={"Tags":"tag", "Name":"description_en", "Measure":"unit"})[["tag", "unit", "description_en"]]], axis=0).drop_duplicates(subset=["tag"])

In [247]:
meta_=meta.copy()

In [202]:
meta=meta_.copy()

In [251]:
meta.shape

(2275, 4)

In [ ]:
ADIOS
meta.head(15)

,tag,unit,description,description_en
0,Time,datetime,Time,Time
1,2-003-UZ001-MD_SPEED-X,M/MIN,Presse : Istwert Geschwindigkeit,Press : Actual Speed
2,2-033-UZ001-MD_SPEED-X,M/MIN,Speedsizer : Istwert Geschwindigkeit,Speedsizer : Actual Speed
3,2-033-FC100-Y,%,Stärke Arbeitsbehälter 1 : Ausgang,Starch Working Container 1 : Output
4,2-033-FC100-X,M3/HR,Stärke Arbeitsbehälter 1 : Messwert,Starch Working Container 1 : Measured Value
5,2-033-FC150-Y,%,Stärke Speedsizer 1 : Ausgang,Starch Speedsizer 1 : Output
6,2-033-FC150-X,M3/HR,Stärke Speedsizer 1 : Messwert,Starch Speedsizer 1 : Measured Value
7,2-033-FC200-Y,%,Stärke Arbeitsbehälter 2 : Ausgang,Starch Working Container 2 : Output
8,2-033-FC200-X,M3/HR,Stärke Arbeitsbehälter 2 : Messwert,Starch Working Container 2 : Measured Value
9,2-033-FC250-Y,%,Stärke Speedsizer 2 : Ausgang,Starch Speedsizer 2 : Output
10,2-033-FC250-X,M3/HR,Stärke Speedsizer 2 : Messwert,Starch Speedsizer 2 : Measured Value
11,2-033-FI100-X,M3/HR,Konz. STärke AB1 : Messwert,Conc. Starch AB1 : Measured Value
12,2-033-FI100-D2-X,,Staerkeauftrag BW : MESSWERT in [ml/m²],Starch Application BW : MEASURED VALUE in [ml/m²]
13,2-033-FI200-X,M3/HR,Konz. STärke AB2 : Messwert,Conc. Starch AB2 : Measured Value
14,2-033-PD110-X,BAR,Diff.Druck Filter 1 AB1 : Messwert,Diff. Pressure Filter 1 AB1 : Measured Value

In [36]:
meta[meta.description_en.str.lower().str.contains("moist")]

,tag,unit,description,description_en
90,QMS11_MIC_MSTSCN2-X1,PCT,Feuchte VTP Speedsizer 0-15%,Moisture VTP Speedsizer 0-15%
97,QMS11_MIC_MSTSCN1-X1,PCT,Feuchte NTP Poperoller 0-15 %,Moisture NTP Poperoller 0-15 %
213,QLS-REEL-MOISTURE2-CUR,,Current reel moisture average(Leimpresse),Current reel moisture average (size press)
214,QLS-REEL-MOISTURE2-LAST,,Last reel moisture average(Leimpresse),Last reel moisture average (size press)
219,QLS-REEL-MOISTURE1-CUR,,Current reel moisture average(Aufrollung),Current reel moisture average (reel-up)
220,QLS-REEL-MOISTURE1-LAST,,Last reel moisture average(Aufrollung),Last reel moisture average (reel-up)
754,2-033-FI100-D3,%,Feuchte nach SpeedSizer [0..50 %],Moisture after SpeedSizer [0..50 %]
2042,PM1-PMSP.OPR:SPA,%,Regler Feuchte Sizer Sollwert [0..30 %],Controller moisture sizer setpoint [0..30 %]
2046,PM1-PMRL.OPR:SPA,%,Regler Feuchte Pope Sollwert [0..30 %],Controller moisture pope setpoint [0..30 %]
2047,PM1-PMSP.OPR:MA,,Regler Feuchte Sizer M/A [0..1 ],Controller moisture sizer M/A [0..1 ]
2048,PM1-PMSP.OPR:ME,%,Regler Feuchte Sizer Messung [0..30 %],Controller moisture sizer measurement [0..30 %]
2049,PM1-PMSP.OPR:POS,bar,Regler Feuchte Sizer Reglerausgang [0..8 bar],Controller moisture sizer controller output [0...
2050,PM1-PMRL.CP:ERRVAR,%,MD COV Feuchte Pope [0..10 %],MD COV moisture pope [0..10 %]
2051,PM1-PMRL.OPR:MA,,Regler Feuchte Pope M/A [0..1 ],Controller moisture pope M/A [0..1 ]
2052,PM1-PMRL.OPR:ME,%,Regler Feuchte Pope Messung [0..30 %],Controller moisture pope measurement [0..30 %]
2053,PM1-PMRL.OPR:POS,bar,Regler Feuchte Pope Reglerausgang [0..8 bar],Controller moisture pope controller output [0....
2054,PM1-PM1-SP:GRAW.MAX,%,Feuchtemessung Sizer Rohprofil Maximalwert [0....,Moisture measurement sizer raw profile maximum...
2055,PM1-PM1-SP:GRAW.MIN,%,Feuchtemessung Sizer Rohprofil Minimumwert [0....,Moisture measurement sizer raw profile minimum...
2056,PM1-PM1-SP:GRAW.SIG,,Feuchtemessung Sizer Rohprofil 2 sigma [0..20 ],Moisture measurement sizer raw profile 2 sigma...
2057,PM1-PM1-TRLT5:CDSIG.COV,%,CD COV Feuchte Pope [0..10 %],CD COV moisture pope [0..10 %]
2095,PM1-MO1-RL:SHPOWER,%,Feuchtemessung Pope interne Luftfeuchte Source...,Moisture measurement Pope internal air humidit...
2096,PM1-MO1-RL:GFLT.SIG,,Feuchtemessung Pope gefiltertes Profil 2 sigma...,Moisture measurement Pope filtered profile 2 s...
2097,PM1-MO1-RL:GRAW.AVG,%,Feuchtemessung Pope Rohprofil Mittelwert [0..3...,Moisture measurement Pope raw profile average ...
2098,PM1-MO1-RL:GRAW.MAX,%,Feuchtemessung Pope Rohprofil Maximalwert [0.....,Moisture measurement Pope raw profile maximum ...
2099,PM1-MO1-RL:GRAW.MIN,%,Feuchtemessung Pope Rohprofil Minimumwert [0.....,Moisture measurement Pope raw profile minimum ...
2100,PM1-MO1-RL:DHTMP,C,Feuchtemessung Pope Temperatur Detector Head [...,Moisture measurement Pope temperature Detector...
2101,PM1-MO1-RL:GFLT.AVG,%,Feuchtemessung Pope gefiltertes Profil Mittelw...,Moisture measurement Pope filtered profile ave...
2102,PM1-MO1-RL:GFLT.MAX,%,Feuchtemessung Pope gefiltertes Profil Maximal...,Moisture measurement Pope filtered profile max...
2103,PM1-MO1-RL:GFLT.MIN,%,Feuchtemessung Pope gefiltertes Profil Minimum...,Moisture measurement Pope filtered profile min...
2104,PM1-MO1-RL:CHOPSPEED,1/min,Feuchtemessung Pope Geschwindigkeit Lichtzerha...,Moisture measurement Pope speed light chopper ...
2105,PM1-MO1-RL:DETTMP,C,Feuchtemessung Pope Temperatur InGaAS detektor...,Moisture measurement Pope temperature InGaAS d...
2106,PM1-MO1-RL:DHHUM,%,Feuchtemessung Pope interne Luftfeuchte Detect...,Moisture measurement Pope internal air humidit...
2107,PM1-MO1-RL:DHPOWER,W,Feuchtemessung Pope Leistungsaufnahme Detector...,Moisture measurement Pope power consumption De...
2124,PM1-PM1-SP:GFLT.MAX,%,Feuchtemessung Sizer gefiltertes Profil Maxima...,Moisture measurement Sizer filtered profile ma...
2125,PM1-PM1-SP:GFLT.MIN,%,Feuchtemessung Sizer gefiltertes Profil Minimu...,Moisture measurement Sizer filtered profile mi...
2126,PM1-PM1-SP:GFLT.SIG,,Feuchtemessung Sizer gefiltertes Profil 2 sigm...,Moisture measurement Sizer filtered profile 2 ...
2127,PM1-PM1-SP:GRAW.AVG,%,Feuchtemessung Sizer Rohprofil Mittelwert [0.....,Moisture measurement Sizer raw profile average...
2131,PM1-PM1-SP:GFLT.AVG,%,Feuchtemessung Sizer gefiltertes Profil Mittel...,Moisture measurement Sizer filtered profile av...
2140,PM1-MZ1-SP-WT:AV,C,Feuchtemessung Sizer Bahntemperatur [0..100 C],Moisture measurement Sizer web temperature [0....
2144,PM1-MZ1-SP:ODWGTIV,g/m2,Feuchtemessung Sizer Otro aktueller Wert [0..1...,Moisture measurement Sizer Otro current value ...
2145,PM1-MZ1-SP:SHHUM,%,Feuchtemessung Sizer interne Luftfeuchte [0..1...,Moisture measurement Sizer internal air humidi...
2146,PM1-MZ1-SP:SHTMP,C,Feuchtemessung Sizer Temperatur [0..100 C],Moisture measurement Sizer temperature [0..100 C]
2147,PM1-MZ1-SP:WWGTIV,g/m2,Feuchtemessung Sizer Wassergewicht aktueller W...,Moisture measurement Sizer water weight curren...
2149,PM1-MZ1-SP:CHOPSPEED,1/min,Feuchtemessung Sizer Geschwindigkeit Lichtzerh...,Moisture measurement Sizer speed light chopper...
2150,PM1-MZ1-SP:LAMPPOWER,W,Feuchtemessung Sizer Leistungsaufnahme Halogen...,Moisture measurement Sizer power consumption h...
2151,PM1-MZ1-SP:MOISTIV,%,Feuchtemessung Sizer Feuchte aktueller Wert [0...,Moisture measurement Sizer moisture current va...
2152,PM1-MO1-RL:SHTMP,C,Feuchtemessung Pope Temperatur Source Head [0....,Moisture measurement Pope temperature Source H...
2226,QO_FEUCHT_NORM_MD,,QO_Feucht NORM MD Normalised MD,QO_Moisture NORM MD Normalised MD
2227,QO_FEUCHT_TOTVAR15,,QO_Feucht TOTVAR15 F13 Total variation moistur...,QO_Moisture TOTVAR15 F13 Total variation moist...
2228,QO_FEUCHT_VAR_CD15,,QO_Feucht VAR CD15 C12 Feucht VAR CD15,QO_Moisture VAR CD15 C12 Moisture VAR CD15
2229,QO_FEUCHT_VAR_MD,,QO_Feucht VAR MD A06 Feucht VAR MD Feucht VAR ...,QO_Moisture VAR MD A06 Moisture VAR MD Moistur...
2230,QO_FEUCHT_2S_CD6,,QO_Feucht 2sCD6 D09,QO_Moisture 2sCD6 D09
2231,QO_FEUCHT_2S_MD,,QO_Feucht 2s MD E10,QO_Moisture 2s MD E10
2232,QO_FEUCHT_2S_TOT15,,QO_Feucht 2s TOT15 G14 Feucht 2s TOT15,QO_Moisture 2s TOT15 G14 Moisture 2s TOT15
2233,QO_FEUCHT_ADJ,,QO_Feucht ADJ Calculation AX-A5 V1.0,QO_Moisture ADJ Calculation AX-A5 V1.0
2237,QO_FEU_AL400,,QO_Feu AL400,QO_Moisture AL400
2271,QO_FEUCHTE_ONLINE,,QO_Feuchte Online Feuchte Poperoller Feuchte O...,QO_Moisture Online Moisture Poperoller Moistur...

In [260]:
import pandas as pd
 
# Create new row as dictionary
new_row = {
    "tag": "R2NAE20CF905",
    "unit": "t/h",
    "description": "Abdampf",
    "description_en": "Waste steam"
}
 
# Append to meta
meta = pd.concat([meta, pd.DataFrame([new_row])], ignore_index=True)
 
# Optional: verify
meta.tail()

,tag,unit,description,description_en
2271,2-008-LC041_05_2-Y,%,Überlauf Stoff-Deculator B41.5 : Stellwert [-1...,Overflow stock deculator B41.5 : Control value...
2272,2-008-LC041_25_2-X,%,Überlauf Verd.wasser-Deculator B41.25 : Messwe...,Overflow dilution water deculator B41.25 : Mea...
2273,2-008-LC041_25_2-W,%,Überlauf Verd.wasser-Deculator B41.25 : Sollwe...,Overflow dilution water deculator B41.25 : Set...
2274,2-008-LC041_25_2-Y,%,Überlauf Verd.wasser-Deculator B41.25 : Stellw...,Überlauf Verd.wasser-Deculator B41.25 : Stellw...
2275,R2NAE20CF905,t/h,Abdampf,Waste steam

In [4]:
import pandas as pd
 
# New tags to add
new_rows = [
    # MF1
    {"description_en": "Multifractor 1 long fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_4-X",
     "description": "Multifraktor 1 Langfaser Durchfluss"},
    {"description_en": "Multifractor 1 short fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_3-X",
     "description": "Multifraktor 1 Kurzfaser Durchfluss"},
    {"description_en": "Multifractor 1 consistency",
     "unit": "%",
     "tag": "1-000-CC005_1_1-X",
     "description": "Multifraktor 1 Stoffdichte"},
 
    # MF2
    {"description_en": "Multifractor 2 long fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_2-X",
     "description": "Multifraktor 2 Langfaser Durchfluss"},
    {"description_en": "Multifractor 2 short fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_1-X",
     "description": "Multifraktor 2 Kurzfaser Durchfluss"},
    {"description_en": "Multifractor 2 consistency",
     "unit": "%",
     "tag": "1-000-CC005_1_2-X",
     "description": "Multifraktor 2 Stoffdichte"},
 
    # MF3
    {"description_en": "Multifractor 3 long fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_8_1-X",
     "description": "Multifraktor 3 Langfaser Durchfluss"},
    {"description_en": "Multifractor 3 short fibre flow",
     "unit": "m³/h",
     "tag": "1-000-FC005_8_2-X",
     "description": "Multifraktor 3 Kurzfaser Durchfluss"},
    {"description_en": "Multifractor 3 consistency",
     "unit": "%",
     "tag": "1-000-CC005_1_3-X",
     "description": "Multifraktor 3 Stoffdichte"},
]
 
new_df = pd.DataFrame(new_rows)
 
# Ensure same column order as meta
new_df = new_df[meta.columns.intersection(new_df.columns)]
 
# Append
meta = pd.concat([meta, new_df], ignore_index=True)
 
# Optional: drop duplicates by tag (safe upsert behaviour)
meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [9]:
import pandas as pd
import numpy as np
 
# New rows to add
new_rows = [
    {
        "description_en": "Condensate energy from paper plant to power plant",
        "description": "Kondensatenergie von der Papierfabrik zum Kraftwerk",
        "unit": np.nan,  # unknown / not provided
        "tag": "GMC_A1_G1LDA10CF701_WF",
        "TagNumber": np.nan,
    },
    {
        "description_en": "Short fibre B06 consistency",
        "description": "Kurzfaser B06 Stoffdichte",
        "unit": "%",
        "tag": "1-000-CC006_01-X",
        "TagNumber": np.nan,
    },
    {
        "description_en": "Long fibre consistency B07",
        "description": "Langfaser B07 Stoffdichte",
        "unit": "%",
        "tag": "1-000-CC007_01-X",
        "TagNumber": 8143,
    },
    {
        "description_en": "Inlet Thickener 2 flow",
        "description": "Zulauf Eindicker 2 Durchfluss",
        "unit": "m3/h",   # normalized from [m3/h]
        "tag": "1-000-FC018_2-X",
        "TagNumber": np.nan,
    },
]
 
new_df = pd.DataFrame(new_rows)
 
# Align to meta columns (keeps only columns that exist in meta)
new_df = new_df.reindex(columns=meta.columns)
 
# Append + upsert by tag
meta = pd.concat([meta, new_df], ignore_index=True)
 
if "tag" in meta.columns:
    meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [10]:
import pandas as pd
import numpy as np
 
new_rows = [
    {
        "description": "Retentionsmittel Menge l/h [0..9000 l/h]",
        "description_en": "Retention aid flow rate",
        "unit": "l/h",
        "tag": "2-008-FC083.01-X",
        "TagNumber": np.nan,
    },
    {
        "description": "Fixiermittelmenge Trockenausschuss [0..100 l/h]",
        "description_en": "Fixing agent flow rate reject",
        "unit": "l/h",
        "tag": "2-008-FC080_02_3-X",
        "TagNumber": np.nan,
    },
    {
        "description": "NaOH-Dosierung Pulper : MESSWERT",
        "description_en": "NaOH dosing pulper: measured value",
        "unit": np.nan,
        "tag": "1-000-FC028_01-X",
        "TagNumber": np.nan,
    },
]
 
new_df = pd.DataFrame(new_rows)
 
# Align with meta structure
new_df = new_df.reindex(columns=meta.columns)
 
# Append + upsert by tag
meta = pd.concat([meta, new_df], ignore_index=True)
 
if "tag" in meta.columns:
    meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [16]:
import pandas as pd
import numpy as np
 
new_rows = [
    {
        "description": "NaOH-Dosierung Kurzfaser-SF :  MESSWERT",
        "description_en": "NaOH dosing short fibre (SF): measured value",
        "unit": np.nan,
        "tag": "1-000-FC028_02-X",
        "TagNumber": np.nan,
    }
]
 
new_df = pd.DataFrame(new_rows)
 
# Align with meta structure
new_df = new_df.reindex(columns=meta.columns)
 
# Append + upsert
meta = pd.concat([meta, new_df], ignore_index=True)
 
if "tag" in meta.columns:
    meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [20]:
import pandas as pd
import numpy as np
 
new_rows = [
    {
        "description": "NaOH-Dosierung Langfaser-SF :  MESSWERT",
        "description_en": "NaOH dosing long fibre (SF): measured value",
        "unit": np.nan,
        "tag": "1-000-FC028_03-X",
        "TagNumber": np.nan,
    }
]
 
new_df = pd.DataFrame(new_rows)
 
# Align with meta structure
new_df = new_df.reindex(columns=meta.columns)
 
# Append + upsert by tag
meta = pd.concat([meta, new_df], ignore_index=True)
 
if "tag" in meta.columns:
    meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [4]:
#HOLA
import pandas as pd
import numpy as np
 
new_rows = [
    {
        "description": "Presse : Istwert Geschwindigkeit",
        "description_en": "Press : Actual Speed",
        "unit": "M/MIN",
        "tag": "2-003-UZ001-MD_SPEED-X",
        "TagNumber": np.nan,
    },
    {
        "description": "Speedsizer : Istwert Geschwindigkeit",
        "description_en": "Speedsizer : Actual Speed",
        "unit": "M/MIN",
        "tag": "2-033-UZ001-MD_SPEED-X",
        "TagNumber": np.nan,
    },
    
]
 
new_df = pd.DataFrame(new_rows)
 
# Align with meta structure
new_df = new_df.reindex(columns=meta.columns)
 
# Append + upsert by tag
meta = pd.concat([meta, new_df], ignore_index=True)
 
if "tag" in meta.columns:
    meta = meta.drop_duplicates(subset="tag", keep="last").reset_index(drop=True)

In [5]:
meta.tail(15)

,tag,unit,description,description_en
2276,1-000-CC005_1_2-X,%,Multifraktor 2 Stoffdichte,Multifractor 2 consistency
2277,1-000-FC005_8_1-X,m³/h,Multifraktor 3 Langfaser Durchfluss,Multifractor 3 long fibre flow
2278,1-000-FC005_8_2-X,m³/h,Multifraktor 3 Kurzfaser Durchfluss,Multifractor 3 short fibre flow
2279,1-000-CC005_1_3-X,%,Multifraktor 3 Stoffdichte,Multifractor 3 consistency
2280,GMC_A1_G1LDA10CF701_WF,None,Kondensatenergie von der Papierfabrik zum Kraf...,Condensate energy from paper plant to power plant
2281,1-000-CC006_01-X,%,Kurzfaser B06 Stoffdichte,Short fibre B06 consistency
2282,1-000-CC007_01-X,%,Langfaser B07 Stoffdichte,Long fibre consistency B07
2283,1-000-FC018_2-X,m3/h,Zulauf Eindicker 2 Durchfluss,Inlet Thickener 2 flow
2284,2-008-FC083.01-X,l/h,Retentionsmittel Menge l/h [0..9000 l/h],Retention aid flow rate
2285,2-008-FC080_02_3-X,l/h,Fixiermittelmenge Trockenausschuss [0..100 l/h],Fixing agent flow rate reject
2286,1-000-FC028_01-X,None,NaOH-Dosierung Pulper : MESSWERT,NaOH dosing pulper: measured value
2287,1-000-FC028_02-X,None,NaOH-Dosierung Kurzfaser-SF : MESSWERT,NaOH dosing short fibre (SF): measured value
2288,1-000-FC028_03-X,None,NaOH-Dosierung Langfaser-SF : MESSWERT,NaOH dosing long fibre (SF): measured value
2289,2-003-UZ001-MD_SPEED-X,M/MIN,Presse : Istwert Geschwindigkeit,Press : Actual Speed
2290,2-033-UZ001-MD_SPEED-X,M/MIN,Speedsizer : Istwert Geschwindigkeit,Speedsizer : Actual Speed

In [1]:
import pandas as pd
meta=pd.read_parquet("complete_tags.parquet")[1:]

In [21]:
meta.tail()

,tag,unit,description,description_en
2285,2-008-FC083.01-X,l/h,Retentionsmittel Menge l/h [0..9000 l/h],Retention aid flow rate
2286,2-008-FC080_02_3-X,l/h,Fixiermittelmenge Trockenausschuss [0..100 l/h],Fixing agent flow rate reject
2287,1-000-FC028_01-X,NaN,NaOH-Dosierung Pulper : MESSWERT,NaOH dosing pulper: measured value
2288,1-000-FC028_02-X,NaN,NaOH-Dosierung Kurzfaser-SF : MESSWERT,NaOH dosing short fibre (SF): measured value
2289,1-000-FC028_03-X,NaN,NaOH-Dosierung Langfaser-SF : MESSWERT,NaOH dosing long fibre (SF): measured value

In [37]:
meta.to_parquet("complete_tags.parquet")

In [2]:
"2-033-UZ001-MD_SPEED-X" in meta.tag.to_list()

False

In [11]:
"2-044-TC413-X" in meta.tag

False

In [15]:
meta[meta.description_en.isin([desc for desc in meta.description_en if "tp4" in desc.lower()])]

,tag,unit,description,description_en
37,2-044-PC404-Y,%,Nulllinie TP4-5 : Ausgang,Zero Line TP4-5 : Output
38,2-044-PC404-X,Pa,Nulllinie TP4-5 : Messwert,Zero Line TP4-5 : Measured Value
39,2-044-PC416-Y,%,Luftmesser TP4 : Ausgang,Air Knife TP4 : Output
40,2-044-PC416-X,Pa,Luftmesser TP4 : Messwert,Air Knife TP4 : Measured Value
41,2-044-PC443-Y,%,Prorelease TP4 : Ausgang,Prorelease TP4 : Output
42,2-044-PC443-X,Pa,Prorelease TP4 : Messwert,Prorelease TP4 : Measured Value
54,2-044-TC413-Y,%,Temp. Zuluft TP4 : Ausgang,Temp. Supply Air TP4 : Output
55,2-044-TC413-X,C,Temp. Zuluft TP4 : Messwert,Temp. Supply Air TP4 : Measured Value
56,2-044-TC413-W,C,Temp. Zuluft TP4 : Sollwert,Temp. Supply Air TP4 : Setpoint
443,QMS11_2-044-V431-N_FU,%,Drehzahl Abluft Ventilator TP4 [0-100 %],Speed exhaust air fan TP4 [0-100 %]
462,QMS11_2-044-V411-N_FU,%,Drehzahl Zuluft Ventilator TP4 [0-100 %],Speed supply air fan TP4 [0-100 %]
694,QMS11_2-044-MC433-X,G/KG,Feuchte Abluft TP4 : Messwert [0..200 g/kg d.a.],Humidity exhaust air TP4 : Measured value [0.....
695,2-044-MC433-Y,%,Feuchte Abluft TP4 : REGLERAUSGANG [0..100 %],Humidity exhaust air TP4 : CONTROLLER OUTPUT [...
1070,2-044-PC416-W,Pa,Luftmesser TP4 : SETPOINT TO CONTROLLER [0..50...,Air Knife TP4 : SETPOINT TO CONTROLLER [0..500...
1324,2-044-TI704_NL,m,Nulllinie TP4+5 [0..2 m],Zero line TP4+5 [0..2 m]
1325,2-044-PC404-W,Pa,Nulllinie TP4-5 : SETPOINT TO CONTROLLER [-50....,Zero line TP4-5 : SETPOINT TO CONTROLLER [-50....
1424,2-044-PC443-W,Pa,Prorelease TP4 : SETPOINT TO CONTROLLER [-5000...,Prorelease TP4 : SETPOINT TO CONTROLLER [-5000...